userObject:
  app:
    name: NoCredApp
    appURL: http://localhost.com
    appPort: "0"
    userDefinedCredentials:
      NoCred:
        Dummy: ""
userInputs:
  InputFile: <<MINIO_FILE_PATH>>
  ConditionConfig: <<MINIO_FILE_PATH>>
  LogFile: <<MINIO_FILE_PATH>>
  CustomInputs: <<MINIO_FILE_PATH>>
fromDate: 2024-09-09
toDate: 2024-09-09
