// This file is autogenerated. Modify as per your task needs.
package main

import (
	googleworkspaceappconnector "applicationtypes/googleworkspaceappconnector"
)

type UserInputs struct {
	googleworkspaceappconnector.GoogleWorkSpaceAppConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}

