package constants

const (
	ErrorCredentialsAlreadyAvailable    = "CredentialTypes already available for this configuration"
	ErrorApplicationAlreadyAvailable    = "ApplicationType already available for this configuration"
	ErrorFolderPathMissing              = "cannot get the folder for CredentialTypes"
	ErrorFileDataMissing                = "file data missing"
	ErrorCannotCreateCredentialsFolder  = "cannot create CredentialTypes folder"
	ErrorCannotCreateCredential         = "cannot create CredentialType"
	ErrorCannotCreateApplication        = "cannot create ApplicationType"
	ErrorCannotCreateSrcFile            = "cannot create source file"
	ErrorCannotCreateGeneratedFile      = "cannot create generated file"
	ErrorCannotFindCredential           = "cannot find credential"
	ErrorCannotReadCredential           = "cannot read credential"
	ErrorCannotUnmarshalCredential      = "cannot unmarshal the credential"
	ErrorCredentialDuplicateAttribute   = "duplicate attributes presented in the spec"
	ErrorCredentialMissing              = "credential missing"
	ErrorMultiSelectNotSupportedForFile = "multi select not supported for files"
	ErrorFileTypeCannotBeSecured        = "File security support has not been implemented yet"
	ErroInvalidData                     = "invalid data"
	ErrorCannotCreateApplicationFolder  = "cannot create applications folder"
	ErrorCannotUnmarshalApplication     = "cannot unmarshal the ApplicationType"
	ErrorCannotFindApplication          = "cannot find the ApplicationType"
	ErrorCannotReadApplication          = "cannot read ApplicationType"
	ErrorCannotGetAuthToken             = "cannot get the auth token"
	ErrorCannotGetApplication           = "cannot get the ApplicationType"
	ErrorAppAlreadyPresent              = "app config already present for this name and version"
	ErrorCredAlreadyPresent             = "credential config already present for this name and version"
	ErrorMoreThanOneAppPresent          = "more than one app is present"
	ErrorCircularDependency             = "circular dependency found"
	ErrorInternalServerError            = "INTERNAL_SERVER_ERROR"
	ErrorInternalServerErrorDescription = "Internal server error"
)
