package constants

const (
	ErrorCredentialsAlreadyAvailable    = "credentials already available for this configuration"
	ErrorApplicationAlreadyAvailable    = "application already available for this configuration"
	ErrorFolderPathMissing              = "cannot get the folder for credentials"
	ErrorFileDataMissing                = "file data missing"
	ErrorCannotCreateCredentialsFolder  = "cannot create credentials folder"
	ErrorCannotCreateCredential         = "cannot create credential"
	ErrorCannotCreateApplication        = "cannot create application"
	ErrorCannotCreateSrcFile            = "cannot create source file"
	ErrorCannotCreateGeneratedFile      = "cannot create generated file"
	ErrorCannotFindCredential           = "cannot find credential"
	ErrorCannotReadCredential           = "cannot read credential"
	ErrorCannotUnmarshalCredential      = "cannot unmarshal the credential"
	ErrorCredentialDuplicateAttribute   = "duplicate attributes presented in the spec"
	ErrorCredentialMissing              = "credential missing"
	ErrorMultiSelectNotSupportedForFile = "multi select not supported for files"
	ErrorFileTypeCannotBeSecured        = "File security support has not been implemented yet"
	ErroInvalidData                     = "invalid data"
	ErrorCannotCreateApplicationFolder  = "cannot create applications folder"
	ErrorCannotUnmarshalApplication     = "cannot unmarshal the application"
	ErrorCannotFindApplication          = "cannot find the application"
	ErrorCannotReadApplication          = "cannot read application"
	ErrorCannotGetAuthToken             = "cannot get the auth token"
	ErrorCannotGetApplication           = "cannot get the application"
	ErrorAppAlreadyPresent              = "app config already present for this name and version"
	ErrorCredAlreadyPresent             = "credential config already present for this name and version"
	ErrorMoreThanOneAppPresent          = "more than one app is present"
	ErrorCircularDependency             = "circular dependency found"
)
