apiVersion: v1alpha1
kind: rule
meta:
  name: FetchGitHubPRCheckRunsGraphQL
  purpose: FetchGitHubPRCheckRunsGraphQL
  description: FetchGitHubPRCheckRunsGraphQL
  labels:
    appType:
    - httprequest
    environment:
    - logical
    execlevel:
    - app
    framework:
    - github
spec:
  inputs:
    CustomExceptionConfigFileForCheckRuns: <<MINIO_FILE_PATH>>
    LogConfigFile: <<MINIO_FILE_PATH>>
    OutputFileFormat: JSON
    PRCheckRunJQConfig: <<MINIO_FILE_PATH>>
    PRCheckRunRequestConfig: <<MINIO_FILE_PATH>>
    PRCheckRunResponseConfig: <<MINIO_FILE_PATH>>
    PRListForInScopeRepos: <<MINIO_FILE_PATH>>
    ProceedIfLogExists: true
    RequiredFields:
    - ResourceID
    RuleOutputFileFormat: PARQUET
  inputsMeta__:
  - name: PRCheckRunRequestConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: PRCheckRunResponseConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: PRListForInScopeRepos
    dataType: FILE
    repeated: false
    format: parquet
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: PRCheckRunJQConfig
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: RequiredFields
    dataType: STRING
    repeated: true
    defaultValue:
    - ResourceID
    allowedValues: []
    showField: true
    required: true
  - name: CustomExceptionConfigFileForCheckRuns
    dataType: FILE
    repeated: false
    format: json
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: RuleOutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: PARQUET
    allowedValues:
    - JSON
    - CSV
    - PARQUET
    - YAML
    - TOML
    - XLSX
    showField: true
    required: true
  - name: LogConfigFile
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ProceedIfLogExists
    dataType: BOOLEAN
    repeated: false
    defaultValue: true
    allowedValues:
    - true
    - false
    showField: true
    required: true
  - name: OutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: JSON
    allowedValues:
    - JSON
    - CSV
    - PARQUET
    - YAML
    - TOML
    - XLSX
    showField: true
    required: true
  tasks:
  - name: ConvertFileFormatV2
    alias: Convert PR List File Format
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: 'Convert files between the supported formats: JSON, CSV, PARQUET,
      YAML, TOML, and XLSX.'
  - name: InputFieldValidation
    alias: Field Validation for InScopeRepos File
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Validates records by ensuring all required fields are present, logging
      errors for missing fields.
  - name: ExecuteHttpRequestV2
    alias: Fetch PR Data
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
      framework:
      - github
    purpose: Purpose of the task
    description: Automate API requests by processing inputs and outputting responses
      in a structured JSON format.
  - name: ConditionalLogGenerator
    alias: Generate Conditional Logs
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: To generate logs by conditions
  - name: ExtractDataUsingJQV2
    alias: Extract PR Check Run Data
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Extracts data from the InputFile based on the provided JQ filter/expression
  - name: CustomExceptionHandler
    alias: Custom Error Message for Exception Handling
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Handles specific exceptions and map generic error messages to user-friendly,
      task-specific messages. It ensures that errors encountered during task execution
      are appropriately managed and presented in a more understandable format.
  - name: ConvertFileFormatV2
    alias: Convert Output File Format
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: 'Convert files between the supported formats: JSON, CSV, PARQUET,
      YAML, TOML, and XLSX.'
  ioMap:
  - Convert PR List File Format.Input.InputFile:=*.Input.PRListForInScopeRepos
  - Convert PR List File Format.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - Convert PR List File Format.Input.ProceedIfLogExists:=*.Input.ProceedIfLogExists
  - Field Validation for InScopeRepos File.Input.InputFile:=Convert PR List File Format.Output.OutputFile
  - Field Validation for InScopeRepos File.Input.RequiredFields:=*.Input.RequiredFields
  - Field Validation for InScopeRepos File.Input.LogFile:=Convert PR List File Format.Output.LogFile
  - Fetch PR Data.Input.RequestConfigFile:=*.Input.PRCheckRunRequestConfig
  - Fetch PR Data.Input.ResponseConfigFile:=*.Input.PRCheckRunResponseConfig
  - Fetch PR Data.Input.InputFile:=Field Validation for InScopeRepos File.Output.ValidDataFile
  - Fetch PR Data.Input.ProceedIfLogExists:=*.Input.ProceedIfLogExists
  - Fetch PR Data.Input.LogFile:=Field Validation for InScopeRepos File.Output.LogFile
  - Generate Conditional Logs.Input.InputFile:=Fetch PR Data.Output.OutputFile
  - Generate Conditional Logs.Input.LogFile:=Fetch PR Data.Output.LogFile
  - Generate Conditional Logs.Input.LogConfigFile:=*.Input.LogConfigFile
  - Generate Conditional Logs.Input.ProceedIfLogExists:=*.Input.ProceedIfLogExists
  - Extract PR Check Run Data.Input.InputFile:=Generate Conditional Logs.Output.OutputFile
  - Extract PR Check Run Data.Input.JQConfigFile:=*.Input.PRCheckRunJQConfig
  - Extract PR Check Run Data.Input.ProceedIfLogExists:=*.Input.ProceedIfLogExists
  - Extract PR Check Run Data.Input.LogFile:=Generate Conditional Logs.Output.LogFile
  - Custom Error Message for Exception Handling.Input.InputFile1:=Extract PR Check
    Run Data.Output.OutputFile
  - Custom Error Message for Exception Handling.Input.LogFile:=Extract PR Check Run
    Data.Output.LogFile
  - Custom Error Message for Exception Handling.Input.CustomExceptionConfigFile:=*.Input.CustomExceptionConfigFileForCheckRuns
  - Convert Output File Format.Input.InputFile:=Custom Error Message for Exception
    Handling.Output.OutputFile1
  - Convert Output File Format.Input.OutputFileFormat:=*.Input.RuleOutputFileFormat
  - Convert Output File Format.Input.ProceedIfLogExists:=*.Input.ProceedIfLogExists
  - Convert Output File Format.Input.LogFile:=Custom Error Message for Exception Handling.Output.LogFile
  - '*.Output.CompliancePCT_:=Convert Output File Format.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=Convert Output File Format.Output.ComplianceStatus_'
  - '*.Output.LogFile:=Convert Output File Format.Output.LogFile'
  - '*.Output.GithubPullRequestCheckRunList:=Convert Output File Format.Output.OutputFile'
