// This file is autogenerated. Modify as per your task needs.
package main

import (
	datadogconnector "applicationtypes/datadogconnector"
)

type UserInputs struct {
	datadogconnector.DatadogConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
    ValidationMessage string
}

