// This file is autogenerated. Modify as per your task needs.
package main

type UserInputs struct {
	AWSCredentialReport string `yaml:"AWSCredentialReport" validate:"required"`
}

type Outputs struct {
	NoAccessKeyWithRootAccount string
	LogFile                    string
}
