id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: PrivacyBisonConnector
  displayName: PrivacyBisonConnector
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - privacybisonconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - privacybisonconnector
spec:
  url: http://privacybison.com
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidatePrivacyBisonConnector
    taskVersion: ""
  credentialTypes:
  - name: NoCred
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: NoCred
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses: []
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
isVersionToBeOverride: true
