authors:
- praveen.kj@continube.com
domain: continube
createdDate: 17/09/2024
name: ConvertFileFormat
displayName: ConvertFileFormat
version: '1.0'
description: Convert files between the supported formats - (JSON, CSV, YAML, TOML, XML, PARQUET)
shaToken: ''
showInCatalog: true
icon: <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122.88 122"><title>product-replacement</title><path d="M120.19,4.78a2,2,0,0,1,1.25.24,2,2,0,0,1,1.15,1.78l.29,39.55a2,2,0,0,1-.95,1.74L105.82,57.7a1.94,1.94,0,0,1-1.16.38l-.32,0L62.49,53.4a2,2,0,0,1-1.86-1.95V11.23A2,2,0,0,1,61.8,9.41l21-9.25a2,2,0,0,1,1-.14l36.32,4.76Zm-79,65.44L29.74,76.74l13.92,1.77,10.47-6.59-12.91-1.7Zm-14.81,10-.58,16.91-6.27-4.27-6.28,3.55,1.28-17.71L3.91,77.36v36.27l38.16,4.24V82.23l-15.66-2Zm-8.75-5L28.8,68.6l-5.53-.73L9.09,74.1l8.57,1.1ZM46,81.66v35l12.37-7.38L58.09,74,46,81.66Zm-.79,40A2,2,0,0,1,44,122a1.72,1.72,0,0,1-.32,0L1.86,117.33a2,2,0,0,1-1.86-2V75.15a1.94,1.94,0,0,1,1.17-1.82l21-9.25a2,2,0,0,1,1-.14L59.55,68.7a2.21,2.21,0,0,1,2.41,2l.28,39.55A1.93,1.93,0,0,1,61.3,112l-16.11,9.61ZM74.3,109.74l6.31-32.08L87,87.31c13.78-5.54,21.52-14.66,22.67-28.7,11.32,19.79,4.45,37.54-9.9,47.93l6.53,9.84-32-6.64ZM50.71,10.44,44.4,42.51,38,32.87C24.22,38.4,16.48,47.52,15.33,61.57,4,41.77,10.88,24,25.23,13.64L18.7,3.8l32,6.64ZM101.85,6.3,90.38,12.82l13.92,1.77L114.76,8,101.85,6.3Zm-14.8,10-.58,16.92L80.19,29,73.92,32.5,75.2,14.8,64.54,13.44V49.71L102.7,54V18.31l-15.65-2Zm-8.75-5,11.13-6.6L83.91,4,69.73,10.18l8.57,1.09Zm28.31,6.47v35L119,45.32l-.25-35.22-12.12,7.64Z"/></svg>
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: InputFile 
  description: Source file containing data in the format (e.g., JSON, CSV, YAML, TOML, XML, PARQUET)
  dataType: FILE 
  repeated: false 
  allowedValues: [] 
  defaultValue:  
  showField: true  
  required: true 
- name: OutputFileFormat
  description: Target format for conversion (e.g., YAML, TOML, CSV, JSON, PARQUET)
  dataType: STRING 
  repeated: false 
  allowedValues: [YAML, TOML, CSV, JSON, PARQUET] 
  defaultValue:  
  showField: true  
  required: true
- name: LogFile 
  description: LogFile of the previous task
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: 
  showField: true
  required: false
- name: OutputFileName 
  description: Name of the output file. Defaults to 'OutputFile' if not specified.
  dataType: STRING 
  repeated: false 
  allowedValues: [] 
  defaultValue:  
  showField: true  
  required: false   
outputs:
- name: OutputFile
  description: Converted file in the specified format.
  dataType: FILE
- name: LogFile
  description: Contains log information in case of task failure
  dataType: FILE
- name: ComplianceStatus_
  description: Compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: Compliance percentage of the task
  dataType: INT