authors:
- divakaran.s@continube.com
domain: continube
createdDate: 29/10/2024
name: GenerateSalesforceUnusedPermissions
displayName: GenerateSalesforceUnusedPermissions
version: '1.0'
description: GenerateSalesforceUnusedPermissions
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: UserDataFile # A unique identifier of the task input
  description: Salesforce user List json file # A concise description of the task input
  dataType: FILE # data type of the input. Available Types STRING, INT, FLOAT, FILE, JSON
  repeated: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: <<MINIO_FILE_PATH>> # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true # boolean: true | false
- name: PermissionsMapFile # A unique identifier of the task input
  description: Used to mp the permmission with eventLogs # A concise description of the task input
  dataType: FILE # data type of the input. Available Types STRING, INT, FLOAT, FILE, JSON
  repeated: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: <<MINIO_FILE_PATH>> # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true # boolean: true | false
- name: EventLogFile # A unique identifier of the task input
  description: Organizaions eventlogFile # A concise description of the task input
  dataType: FILE # data type of the input. Available Types STRING, INT, FLOAT, FILE, JSON
  repeated: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: <<MINIO_FILE_PATH>> # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true # boolean: true | false
outputs:
- name: OutputFile
  description: Users unused permission list
  dataType: FILE
- name: LogFile
  description: Error Log
  dataType: FILE
- name: ComplianceStatus_
  description: Compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: Compliance percentage of the task
  dataType: INT
