userObject:
  app:
    name: HttpRequest
    appURL: "$SALESFORCE_INSTANCE_URL"
    appPort: "0"
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      APIKey:
        APIKey: 
        ValidationCURL:
      AWSSignature:
        AccessKey: 
        SecretKey: 
        ValidationCURL: 
      BasicAuthentication:
        UserName: 
        Password: 
        ValidationCURL: 
      BearerToken:
        Token: 
        ValidationCURL: 
      CustomType:
        ValidationCURL: "$VALIDATION_CURL"
        CredentialJson: "$CREDENTIAL_JSON"
      NoAuth:
      OAuth:
        ClientID: 
        ClientSecret: 
        ValidationCURL: 
      JWTBearer:
          Algorithm: 
          Payload: 
          PrivateKey: 
          ValidationCURL:  
userInputs:
  UserDataFile: <<MINIO_FILE_PATH>>
  PermissionsMapFile: <<MINIO_FILE_PATH>>
  EventLogFile: <<MINIO_FILE_PATH>>
fromDate: 2024-10-29T06:44:00Z
toDate: 2024-10-29T06:44:00Z
