
[Variables]

[Request]

URL = "<<inputfile.url>>/pulls"

Method = "GET"

ContentType = ""

Redirect = true

CredentialType = "BearerToken"

TimeOut = 30

Verify = true

Retries = 3

RetryOnStatus = [503, 504, 429]


[Request.Headers]
Accept = "application/vnd.github.groot-preview+json"
XGitHubApiVersion = "2022-11-28"

