package awsappconnector

const (
	CLOUDTRAIL                = "AwsCloudTrailTrail"
	CLOUDTRAIL_LIST           = "AwsCloudTrailTrailList"
	KMS                       = "AwsKmsKey"
	VPC                       = "AwsEc2Vpc"
	CLOUD_WATCH_METRIC_ALARM  = "AwsCloudWatchMetricAlaram"
	CLOUD_WATCH_METRIC_FILTER = "AwsCloudWatchMetricFilter"
	IAM_USER                  = "AwsIamUser"
	IAM_USER_LIST             = "AwsIamUserList"
	IAM_ROLE                  = "AwsIamRole"
	IAM_GROUP                 = "AwsIamGroup"
	IAM_POLICY                = "AwsIamPolicy"
	IAM_PASSWORD_POLICY       = "AwsIamPasswordPolicy"
	CLOUD_WATCH_LOG_GRP       = "LogGroup"
	S3_BUCKET                 = "AwsS3Bucket"
	BACKUP_VAULT              = "AwsBackupBackupVault"
	BACKUP_RECOVERY_PT        = "AwsBackupRecoveryPoint"
	CLOUD_WATCH_METRICS_LIST  = "AwscloudWatchMetricList"
	EC2_SECURITY_GROUP        = "AwsEc2SecurityGroup"
	RDS_DB_INSTANCE           = "AwsRdsDbInstance"
	EC2_INSTANCE              = "AwsEc2Instance"
	DYNAMO_DB_INSTANCE        = "AwsDynamoDBInstance"
	ELASTIC_CACHE             = "AwsElasticCacheInstance"
	TIMESTREAM_INSTANCE       = "AwsTimeStreamInstance"
	NEPTUNE_INSTANCE          = "AwsNeptuneInstance"
	DOC_DB_INSTANCE           = "AwsDocdbInstance"
	QLDB_LEDGER               = "AwsQLDBInstance"
	KEYSPACES                 = "AwsKeyspaces"
	CLOUDFRONT_DISTRIBUTION   = "AwsCloudfrontDistribution"
	DIRECTCONNECT_CONNECTION  = "AwsDirectConnect"
	ROUTE_53                  = "AwsRoute53"
	NETWORK_FIREWALL          = "AwsNetworkFirewall"
)
