[JQConfig]
JQExpression = "[.[0].items[] | {HelmReleaseName: (.metadata.labels.name // \"unknown\"), HelmNamespace: .metadata.namespace, HelmStatus: (.metadata.labels.status // \"unknown\"), HelmOwner: (.metadata.labels.owner // \"unknown\"), SecretName: .metadata.name}]"
OutputMethod = "FIRST"
