
[Response.RuleSet]
    [Response.RuleSet.AppendColumnCondition]
    ConditionField = "<<response.status_code>>"
    ConditionValue = "200"

    [Response.RuleSet.AppendColumn]
    IncludeAllInputFields = true

    [Response.RuleSet.PaginationCondition]
    ConditionField = "<<response.links.next>>"
    ConditionValue = ""

    [Response.RuleSet.Pagination]
        URL = "<<response.links.next.url>>"