// This file is autogenerated. Modify as per your task needs.
package main

import (
	compliancecow "appconnections/compliancecow"
)

type UserInputs struct {
	compliancecow.ComplianceCow `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}

