// This file is autogenerated. Modify as per your task needs.
package main

import (
	snykappconnector "appconnections/snykappconnector"
)

type UserInputs struct {
	snykappconnector.SnykAppConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
    ValidationMessage string
}

