[Request]
URL = "<<application.AppURL>>/repos/<<inputfile.account_owner>>/<<inputfile.repository_name>>/dependabot/alerts?per_page=100"
Method = "GET"
ContentType = "application/json"
Redirect = true
CredentialType = "BearerToken"
TimeOut = 30  
Retries = 3  
RetryOnStatus = [503]
Verify=true
