[Response]

[Response.RuleSet]

    [Response.RuleSet.AppendColumnCondition]
    ConditionField = "<<response.status_code>>"
    ConditionValue = "200"

    [Response.RuleSet.AppendColumn]
    IncludeAllInputFields = true

    [Response.RuleSet.AppendColumn.Fields]
    dummy_field = "dummy_value" 

    [Response.RuleSet.PaginationCondition]
    ConditionField = "<<response.links.next>>"
    ConditionValue = ""
 
    [Response.RuleSet.Pagination]
        URL = "<<response.links.next.url>>"
        [Response.RuleSet.Pagination.Header]
        
        [Response.RuleSet.Pagination.Params]
        
        [Response.RuleSet.Pagination.Data.URLEncoded]