[AddColumn]
"System" = "github"
"Source" = "compliancecow"
"ResourceID" = "N/A"
"ResourceName" = "<<inputfile1.account_owner>>/<<inputfile1.repository_name>>"
"ResourceType" = "Repository"
"ResourceLocation" = "<<inputfile1.dependency.manifest_path>>"
"ResourceTags" = "N/A"
"ResourceURL" = "<<inputfile1.html_url>>"
"VulnerabilityAlertNumber" = "<<inputfile1.number>>"
"GHSAID" = "<<inputfile1.security_advisory.ghsa_id>>"
"VulnerabilitySummary" = "<<inputfile1.security_advisory.summary>>"
"VulnerabilityDescription" = "<<inputfile1.security_advisory.description>>"
"Package" = "<<inputfile1.security_vulnerability.package.name>> (<<inputfile1.security_vulnerability.package.ecosystem>>)"
"VulnerableVersionRange" = "<<inputfile1.security_vulnerability.vulnerable_version_range>>"
"FirstPatchedVersion" = "<<inputfile1.security_vulnerability.first_patched_version.identifier>>"
"State" = "<<inputfile1.state>>"
"FixedAt" = "<<inputfile1.fixed_at>>"
"DismissedBy" = "<<inputfile1.dismissed_by.login>>"
"DismissedAt" = "<<inputfile1.dismissed_at>>"
"DismissedReason" = "<<inputfile1.dismissed_reason>>"
"DismissedComment" = "<<inputfile1.dismissed_comment>>"
"AutoDismissedAt" = "<<inputfile1.auto_dismissed_at>>"
"Severity" = "<<inputfile1.security_advisory.severity>>"
"CVEID" = "<<inputfile1.security_advisory.cve_id>>"
"CVSSV4Vector" = "<<inputfile1.security_advisory.cvss_severities.cvss_v4.vector_string>>"
"CVSSV4Score" = "<<inputfile1.security_advisory.cvss_severities.cvss_v4.score>>"
"CWEs" = "<<inputfile1.security_advisory.cwes>>"
"GHSAReferences" = "<<inputfile1.security_advisory.references>>"
"ValidationStatusCode" = "<<inputfile1.validation_status_code>>"
"ValidationStatusNotes" = "<<inputfile1.validation_status_notes>>"
"ComplianceStatus" = "<<inputfile1.compliance_status>>"
"ComplianceStatusReason" = "<<inputfile1.compliance_status_reason>>"
"EvaluatedTime" = "<<inputfile1.updated_at>>"
"UserAction" = ""
"ActionStatus" = ""
"ActionResponseURL" = ""
[ReorderColumn]
"ColumnList" = "System,Source,ResourceID,ResourceName,ResourceType,ResourceLocation,ResourceTags,ResourceURL,VulnerabilityAlertNumber,GHSAID,VulnerabilitySummary,VulnerabilityDescription,Package,VulnerableVersionRange,FirstPatchedVersion,State,FixedAt,DismissedBy,DismissedAt,DismissedReason,DismissedComment,AutoDismissedAt,Severity,CVEID,CVSSV4Vector,CVSSV4Score,CWEs,GHSAReferences,ValidationStatusCode,ValidationStatusNotes,ComplianceStatus,ComplianceStatusReason,EvaluatedTime,UserAction,ActionStatus,ActionResponseURL"