apiVersion: v1alpha1
kind: rule
meta:
  name: CreateJiraIssueWithTemplate
  purpose: This rule creates a Jira issue using a provided jira issue template (currently uses jira rest api version 3).
  description: Creates Jira issue based on the given issue fields.
  labels:
    appType:
    - jiracloud
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - jiracloud
spec:
  inputs:
    JiraIssueTemplate: <<MINIO_FILE_URL>>
  inputsMeta__:
  - name: JiraIssueTemplate
    description: The Jira issue template file to be used for creating the issue.
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_URL>>
    allowedValues: []
    showField: true
    required: true
  outputsMeta__:
  - name: CreatedTicket
    description: The created Jira ticket (contains ticket key and id).
    dataType: FILE
    repeated: false
    defaultValue:  <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
    required: true
  - name: LogFile
    description: File that contains information about errors that have occurred while the execution of the rule.
    dataType: FILE
    repeated: false
    defaultValue:  <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ComplianceStatus_
    description: Percentage indicating rule's compliance.
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  - name: CompliancePCT_
    description: Status indicating the rule's compliance.
    dataType: INT
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: CreateJiraIssueWithTemplate
    alias: t1
    type: task
    appTags:
      appType:
      - jiracloud
      environment:
      - logical
      execlevel:
      - app
    purpose: Create a Jira issue using the provided template.
    description: Creates a Jira issue in Jira Cloud using the specified issue template file.
  ioMap:
  - t1.Input.JiraIssueTemplate:=*.Input.JiraIssueTemplate
  - '*.Output.CreatedTicket:=t1.Output.CreatedTicket'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
