apiVersion: v1alpha1
kind: rule
meta:
  name: SnykContainerVulnerabilityScanner
  purpose: This rule scans projects to identify vulnerability issues, capturing detailed data such as CVE IDs and other standardized fields. The results are formatted, ensuring consistent and comprehensive reporting of security issues.
  description: This rule scans projects to identify vulnerability issues, capturing detailed data such as CVE IDs and other standardized fields. The results are formatted, ensuring consistent and comprehensive reporting of security issues.
  labels:
    appType:
    - snykappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - snykappconnector
spec:
  inputs:
    IncludeCriteria: 
    ExcludeCriteria: 
  inputsMeta__:
  - name: IncludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  - name: ExcludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: SnykContainerVulnerabilityScanner
    alias: t1
    type: task
    appTags:
      appType:
      - snykappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: This task scans projects to identify vulnerability issues, capturing detailed data such as CVE IDs and other standardized fields. The results are formatted, ensuring consistent and comprehensive reporting of security issues.
    description: This task scans projects to identify vulnerability issues, capturing detailed data such as CVE IDs and other standardized fields. The results are formatted, ensuring consistent and comprehensive reporting of security issues.
  ioMap:
  - 't1.Input.IncludeCriteria:=*.Input.IncludeCriteria'
  - 't1.Input.ExcludeCriteria:=*.Input.ExcludeCriteria'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.SnykContainerScannerReport:=t1.Output.SnykContainerScannerReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
