// This file is autogenerated. Modify as per your task needs.
package main

import (
	teamcityconnector "applicationtypes/teamcityconnector"
)

type UserInputs struct {
	teamcityconnector.TeamCityConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
