apiVersion: v1alpha1
kind: rule
meta:
  name: GithubBranchSettingsReport
  purpose: Github Branch Settings Report
  description: Github Branch Settings Report
  labels:
    appType:
    - githubconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - githubconnector
spec:
  inputs:
    CriteriaConfig: <<MINIO_FILE_PATH>>
    MinimumRequiredReviewersCount: 
  inputsMeta__:
  - name: CriteriaConfig
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: MinimumRequiredReviewersCount
    dataType: INTEGER
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: GithubBranchSettingsReport
    alias: t1
    type: task
    purpose: Github Branch Settings Report
    description: Github Branch Settings Report
  ioMap:
  - t1.Input.CriteriaConfig:=*.Input.CriteriaConfig
  - t1.Input.MinimumRequiredReviewersCount:=*.Input.MinimumRequiredReviewersCount
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.GithubBranchSettingsReport:=t1.Output.GithubBranchSettingsReport'

