// This file is autogenerated. Modify as per your task needs.
package main

import (
	argocdconnector "appconnections/argocdconnector"
)

type UserInputs struct {
	argocdconnector.ArgoCDConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
    ValidationMessage string
}

