apiVersion: v1alpha1
kind: rule
meta:
  name: SalesForceUnusedPermissions
  purpose: To get salseforce user's unused permissions
  description: To get salesforce user's unused permissions
  labels:
    appType:
    - httprequest
    environment:
    - logical
    execlevel:
    - app
spec:
  inputs:
    ExtractPath: .[0].records
    OutputFileFormat: JSON
    OutputMethod: FIRST
    SalesforceOrganizationEventLogRequestConfigFile: <<MINIO_FILE_PATH>>
    SalesforceOrganizationEventLogResponseConfigFile: <<MINIO_FILE_PATH>>
    SalesforcePermissionsMapFile: <<MINIO_FILE_PATH>>
    SalesforceUserPermissionSetTransformConfigFile: <<MINIO_FILE_PATH>>
    SalesforceUsersListRequestConfigFile: <<MINIO_FILE_PATH>>
    SalesforceUsersPermissionSetRequestConfigFile: <<MINIO_FILE_PATH>>
    SalesforceUsersPermissionSetResponseConfigFile: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: SalesforceUsersListRequestConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ExtractPath
    dataType: JQ_EXPRESSION
    explanation: 
    repeated: false
    defaultValue: .[0].records
    allowedValues: []
    showField: true
    required: true
  - name: SalesforceUsersPermissionSetRequestConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: SalesforceUsersPermissionSetResponseConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: SalesforceOrganizationEventLogRequestConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: SalesforceOrganizationEventLogResponseConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: SalesforceUserPermissionSetTransformConfigFile
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: SalesforcePermissionsMapFile
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: OutputMethod
    dataType: STRING
    repeated: false
    defaultValue: FIRST
    allowedValues:
    - FIRST
    - ALL
    showField: true
    required: true
  - name: OutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: JSON
    allowedValues:
    - JSON
    - CSV
    - PARQUET
    showField: true
    required: true
  tasks:
  - name: ExecuteHttpRequestV2
    alias: Get Users List
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    purpose: To get the list of users in the organization 
    description: To get the list of users in the organization 
  - name: ExtractDataUsingJQV2
    alias: t2
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: To extract the data 
    description: ExtractDataUsingJQ
  - name: ExecuteHttpRequestV2
    alias: Get User's permission sets
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    purpose: To get user's permission sets
    description: To get user's permission sets
  - name: TransformDataV2
    alias: t4
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: To transform the data
    description: To transform the data
  - name: ExecuteHttpRequestV2
    alias: Get Organization's EventLog
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    purpose: To get organizarions EventLog
    description: To get organizarions EventLog
  - name: GenerateSalesforceUnusedPermissions
    alias: t7
    type: task
    appTags:
        appType:
        - httprequest
        environment:
        - logical
        execlevel:
        - app
    purpose: GenerateSalesforceUnusedPermissions
    description: GenerateSalesforceUnusedPermissions
  ioMap:
  - Get Users List.Input.RequestConfigFile:=*.Input.SalesforceUsersListRequestConfigFile
  - t2.Input.InputFile:=Get Users List.Output.OutputFile
  - t2.Input.JQExpression:=*.Input.ExtractPath
  - t2.Input.OutputMethod:=*.Input.OutputMethod
  - t2.Input.LogFile:=Get Users List.Output.LogFile
  - Get User's permission sets.Input.RequestConfigFile:=*.Input.SalesforceUsersPermissionSetRequestConfigFile
  - Get User's permission sets.Input.ResponseConfigFile:=*.Input.SalesforceUsersPermissionSetResponseConfigFile
  - Get User's permission sets.Input.InputFile:=t2.Output.OutputFile
  - Get User's permission sets.Input.LogFile:=t2.Output.LogFile
  - t4.Input.InputFile1:=Get User's permission sets.Output.OutputFile
  - t4.Input.TransformConfigFile:=*.Input.SalesforceUserPermissionSetTransformConfigFile
  - t4.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - t4.Input.LogFile:=Get User's permission sets.Output.LogFile
  - Get Organization's EventLog.Input.RequestConfigFile:=*.Input.SalesforceOrganizationEventLogRequestConfigFile
  - Get Organization's EventLog.Input.ResponseConfigFile:=*.Input.SalesforceOrganizationEventLogResponseConfigFile
  - Get Organization's EventLog.Input.LogFile:=t4.Output.LogFile
  - t7.Input.UserDataFile:=t4.Output.OutputFile
  - t7.Input.PermissionsMapFile:=*.Input.SalesforcePermissionsMapFile
  - t7.Input.EventLogFile:=Get Organization's EventLog.Output.OutputFile
  - '*.Output.CompliancePCT_:=Get Organization''s EventLog.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=Get Organization''s EventLog.Output.ComplianceStatus_'
  - '*.Output.LogFile:=Get Organization''s EventLog.Output.LogFile'
  - '*.Output.UsersUnusedPermissions:=t7.Output.OutputFile'
