apiVersion: v1alpha1
kind: credentialType
meta:
  name: JIRACredential # <name of the credential type. Examples, activeDirectory>
  displayName:  JIRA Credential - CLI Auth Displayable # <optional. How do you want this to show up in the ComplianceCow UI. Example, Active Directory> 
  shortDescription: This is a real time authentication cred type for JIRA CLI short description # optional
  longDescription: This is a real time authentication cred type for JIRA CLI long description # optional
  labels: # optional. This will be used by the selectors in Application Class to identify credential types
    type: [jiracliauth]
  annotations: # optional. These are user defined labels for reporting purposes
    jiraannotation: [jiracliauth]  
  version: 1.1.1
  verbs: # optional
  - singular: credentialtype
    plural: credentialtypes
  - singular: ct
    plural: cts
spec:
 extends: [] # optional. The attributes section will add to the extended attributes
 attributes:
 - name: UserID
   displayName: User ID
   secret: false # optional. boolean: true | false. If true, this attribute value should go to the vault
   required: true # boolean: true | false
   multiSelect: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
   dataType: STRING # data type of the attribute.  string, []string, numeric, []numeric, datetime, file
   allowedValues: # optional. only available when multi select == true. Comma separated string or numeric
   defaultValue: # optional. If multi select == true then comma separated string or numeric
 - name: password
   displayName: Password
   secret: true # optional. boolean: true | false. If true, this attribute value should go to the vault
   required: true # boolean: true | false
   multiSelect: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
   dataType: STRING # data type of the attribute.  string, []string, numeric, []numeric, datetime, file
   allowedValues: # optional. only available when multi select == true. Comma separated string or numeric
   defaultValue: # optional. If multi select == true then comma separated string or numeric