id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: AWSRole
  displayName: AWSRole
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes:
  - name: AccessKey
    displayName: AccessKey
    secret: true
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: SecretKey
    displayName: SecretKey
    secret: true
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: RoleARN
    displayName: RoleARN
    secret: true
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
status: null
isVersionToBeOverride: false
