FROM ghcr.io/opensecuritycompliance/goose:ccbase51125

LABEL MAINTAINER=arul.g@continube.com

COPY ./src/oscgoose/config/config.yaml /root/.config/goose/config.yaml
COPY ./src/oscgoose/config/config.yaml /home/goose/.config/goose/config.yaml

# Create a folder if it doesn't exist
RUN mkdir -p /home/goose/.config/goose/custom_providers

COPY ./src/oscgoose/config/custom_anthropic_custom.json /home/goose/.config/goose/custom_providers/custom_anthropic_custom.json

ENTRYPOINT ["goose", "web", "--host", "0.0.0.0", "--port", "8080"]
