FROM ghcr.io/opensecuritycompliance/opensecuritycompliance/ccowmcpclient:1.1-20260207035035

LABEL MAINTAINER=arul.g@continube.com

COPY ./src/ccowmcpclient/config/config.yaml /home/ccowclient/.local/share/ccowmcp/config/config.yaml

# Create a folder if it doesn't exist
RUN mkdir -p /home/ccowclient/.local/share/ccowmcp/config/custom_providers

COPY ./src/ccowmcpclient/config/custom_anthropic_custom.json /home/ccowclient/.local/share/ccowmcp/config/custom_providers/custom_anthropic_custom.json

ENTRYPOINT ["goose", "web", "--host", "0.0.0.0", "--port", "8080"]
