id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: SemgrepConnector
  displayName: SemgrepConnector
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - semgrepconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - semgrepconnector
spec:
  url: https://semgrep.dev
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidateSemgrepConnector
    taskVersion: ""
  credentialTypes:
  - name: AccessToken
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: AccessToken
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses: []
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
isVersionToBeOverride: true
