apiVersion: v1alpha1
kind: rule
meta:
  name: TrivyContainerVulnerabilityScanner
  purpose: Scans container images for vulnerabilities using the Trivy CLI and retrieves data directly from the CLI output.
  description: Scans container images for vulnerabilities within container images using the Trivy CLI. Retrieves and processes vulnerability data from the CLI output to assess compliance and risk levels.
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    IncludeCriteria: 
    ExcludeCriteria: 
  inputsMeta__:
  - name: IncludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  - name: ExcludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: TrivyContainerVulnerabilityScanner
    alias: t1
    type: task
    purpose: Scans container images for vulnerabilities using the Trivy CLI and retrieves data directly from the CLI output.
    description: Executes the Trivy CLI to analyze container images for vulnerabilities. Retrieves and processes the output to generate reports on detected vulnerabilities, including severity levels and compliance status.
  ioMap:
  - 't1.Input.IncludeCriteria:=*.Input.IncludeCriteria'
  - 't1.Input.ExcludeCriteria:=*.Input.ExcludeCriteria'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.TrivyContainerScannerReport:=t1.Output.TrivyContainerScannerReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
