[AddColumn]
UserAction = ''
ActionStatus = ''
ActionResponseURL = ''

[[AddColumn.ByFunction]]
ColumnName = "EvaluatedTime"         
Source = ""
Function = "CurrentDateTime"

[ReorderColumn]
"ColumnList" = "System,Source,ResourceID,ResourceName,ResourceType,ResourceLocation,ResourceTags,ResourceURL,Project,Priority,SLAInDays,Status,CreatedDate,UpdatedDate,ClosedDate,Creator,Assignee,Reporter,ValidationStatusCode,ValidationStatusNotes,ComplianceStatus,ComplianceStatusReason,EvaluatedTime,UserAction,ActionStatus,ActionResponseURL"
