[AddColumn]
System = "snowflake"
Source = "compliancecow"
ResourceType = "Issue"
ResourceTags = ""
ResourceLocation = "N/A"
UserAction = ""
ActionStatus = ""
ActionResponseURL = ""

[[AddColumn.ByFunction]]
ColumnName = "EvaluatedTime"         
Source = ""
Function = "CurrentDateTime"

[UpdateColumn]
ResourceID = "<<inputfile1.RESOURCEID>>"
ResourceName = "<<inputfile1.RESOURCENAME>>"
ResourceURL = "<<inputfile1.RESOURCEURL>>"
Project = "<<inputfile1.PROJECT>>"
Priority = "<<inputfile1.PRIORITY>>"
SLAInDays = "<<inputfile1.SLA_IN_DAYS>>"
Status = "<<inputfile1.STATUS>>"
CreatedDate = "<<inputfile1.CREATED_DATE>>"
UpdatedDate = "<<inputfile1.UPDATED_DATE>>"
ClosedDate = "<<inputfile1.CLOSED_DATE>>"
Creator = "<<inputfile1.CREATOR>>"
Assignee = "<<inputfile1.ASSIGNEE>>"
Reporter = "<<inputfile1.REPORTER>>"


[ReorderColumn]
"ColumnList" = "System,Source,ResourceID,ResourceName,ResourceType,ResourceLocation,ResourceTags,ResourceURL,Project,Priority,SLAInDays,Status,CreatedDate,UpdatedDate,ClosedDate,Creator,Assignee,Reporter,ValidationStatusCode,ValidationStatusNotes,ComplianceStatus,ComplianceStatusReason,EvaluatedTime,UserAction,ActionStatus,ActionResponseURL"