# inputfile1 -> JiraIssuesList
# inputfile2 -> JiraIssueSLAConfig

SQLQuery = '''
SELECT 
    inputfile1.RESOURCEID,
    inputfile1.RESOURCENAME,
    inputfile1.RESOURCEURL,
    inputfile1.PROJECT,
    inputfile1.PRIORITY,
    COALESCE(inputfile2.SLAInDays, 0) AS SLA_IN_DAYS,
    inputfile1.STATUS,
    inputfile1.CREATED_DATE,
    inputfile1.UPDATED_DATE,
    inputfile1.CLOSED_DATE,
    inputfile1.CREATOR,
    inputfile1.ASSIGNEE,
    inputfile1.REPORTER
FROM inputfile1
LEFT JOIN inputfile2 ON 
    inputfile1.PRIORITY = inputfile2.Priority
WHERE inputfile1.STATUS = 'Closed';
'''
