authors:
- rufus.p@continube.com
domain: continube
createdDate: 30/09/2024
name: FetchGCPDataBaseInstanceList
displayName: FetchGCPDataBaseInstanceList
version: '1.0'
description: FetchGCPDataBaseInstanceList
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: IncludeProjects 
  description: IncludeProjects
  dataType: STRING 
  repeated: false 
  allowedValues: [] 
  defaultValue:  
  showField: true  
  required: false 
- name: ExcludeProjects 
  description: ExcludeProjects
  dataType: STRING 
  repeated: false 
  allowedValues: [] 
  defaultValue:  
  showField: true  
  required: false 
outputs:
- name: GCPDataBaseInstanceList
  description: GCPDataBaseInstanceList
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
