apiVersion: v1alpha1
kind: rule
meta:
  name: ListGoogleWorkSpaceUserList
  purpose: List Google Work Space User List
  description: List Google Work Space User List
  labels:
    appType:
    - googleworkspaceappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - googleworkspaceappconnector
spec:
  tasks:
  - name: ListGoogleWorkSpaceUserList
    alias: t1
    type: task
    purpose: List Google Work Space User List
    description: List Google Work Space User List
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.GooogleWorkSpaceUserList:=t1.Output.GooogleWorkSpaceUserList'
