[[ConditionRules]]
    ConditionLabel = "check_iam_config_contains"
    Condition = "CONTAINS"
    ConditionField = "<<inputfile>>"
    ConditionValue = "iamConfiguration"

[[ConditionRules]]
    ConditionLabel = "check_iam_config_not_empty"
    Condition = "NOT_EMPTY"
    ConditionField = "<<inputfile.iamConfiguration>>"

[ConditionRulesConfig]
    ConditionsCriteria = "check_iam_config_contains && check_iam_config_not_empty"

[[ConditionFieldUpdates]]
    ConditionsCriteria = "check_iam_config_contains && check_iam_config_not_empty"
    
    [ConditionFieldUpdates.FAIL]
        PAP = "N/A"
        UBLA = "N/A"
        ValidationStatusCode = "IAM_CONF_MSNG"
        ValidationStatusNotes = "The bucket lacks an 'iamConfiguration' block, making it impossible to assess IAM compliance."
        ComplianceStatus = "NON_COMPLIANT"
        ComplianceStatusReason = "IAM configuration settings are missing, preventing security validation."
