[[ConditionRules]]
    ConditionLabel = "check_iam_config_PAP"
    Condition = "EQUALS"
    ConditionField = "<<inputfile.iamConfiguration.publicAccessPrevention>>"
    ConditionValue = "enforced"

[ConditionRulesConfig]
    ConditionsCriteria = "check_iam_config_PAP"

[[ConditionFieldUpdates]]
    ConditionsCriteria = "check_iam_config_PAP"

    [ConditionFieldUpdates.PASS]
        PAP = "<<inputfile.iamConfiguration.publicAccessPrevention>>"
    
    [ConditionFieldUpdates.FAIL]
        PAP = "<<inputfile.iamConfiguration.publicAccessPrevention>>"
        UBLA = "<<inputfile.iamConfiguration.uniformBucketLevelAccess.enabled>>"
        ValidationStatusCode = "PAP_NOT_ENF"
        ValidationStatusNotes = "'publicAccessPrevention' is not 'enforced', allowing potential public access."
        ComplianceStatus = "NON_COMPLIANT"
        ComplianceStatusReason = "Public access prevention is not explicitly enforced, increasing exposure risk."
