apiVersion: v1alpha1
kind: rule
meta:
  name: GoogleWorkSpaceManagedDevicesReport
  purpose: Generate google workspace mobile device standard report
  description: Generate google workspace mobile device standard report
  labels:
    appType:
    - googleworkspaceappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - googleworkspaceappconnector
spec:
  inputs:
    MobileDevicesReport: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: MobileDevicesReport
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: GoogleWorkSpaceManagedDevicesReport
    alias: t1
    type: task
    purpose: Generate google workspace mobile device standard report
    description: Generate google workspace mobile device standard report
  ioMap:
  - t1.Input.MobileDevicesReport:=*.Input.MobileDevicesReport
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.GoogleWorkSpaceManagedDeviceReport:=t1.Output.GoogleWorkSpaceManagedDeviceReport'
