// This file is autogenerated. Modify as per your task needs.
package main

import (
	jira "applicationtypes/jiracloud"
)

type UserInputs struct {
	jira.JiraCloud `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
