apiVersion: v1alpha1
kind: rule
meta:
  name: IntuneConditionalAccessPolicies
  purpose: Intune Conditional Access Policies
  description: Intune Conditional Access Policies
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: IntuneConditionalAccessPolicies
    alias: t1
    type: task
    purpose: Intune Conditional Access Policies
    description: Intune Conditional Access Policies
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.IntuneConditionalAccessPolicies:=t1.Output.IntuneConditionalAccessPolicies'
