apiVersion: v1alpha1
kind: rule
meta:
  name: IntunePrivilegedUserConditionalAccessPolicies
  purpose: Intune Privileged User Conditional Access Policies
  description: Intune Privileged User Conditional Access Policies
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    appType:
    - azureappconnector
spec:
  inputs:
    IntuneConditionalAccessPolicies: <<MINIO_FILE_PATH>>
    IntuneUserRegistrationDetails: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: IntuneUserRegistrationDetails
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: IntuneConditionalAccessPolicies
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: IntunePrivilegedUserConditionalAccessPolicies
    alias: t1
    type: task
    purpose: Intune Privileged User Conditional Access Policies
    description: Intune Privileged User Conditional Access Policies
  ioMap:
  - 't1.Input.IntuneConditionalAccessPolicies:=*.Input.IntuneConditionalAccessPolicies'
  - 't1.Input.IntuneUserRegistrationDetails:=*.Input.IntuneUserRegistrationDetails'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.IntunePrivilegedConsoleAccessReport:=t1.Output.IntunePrivilegedConsoleAccessReport'
