apiVersion: v1alpha1
kind: rule
meta:
  name: GetTeamCityUsers
  purpose: GetTeamCityUsers
  description: GetTeamCityUsers
  labels:
    appType:
    - teamcityconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - teamcityconnector
spec:
  tasks:
  - name: GetTeamCityUsers
    alias: t1
    type: task
    purpose: GetTeamCityUsers
    description: GetTeamCityUsers
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.TeamCityUsers:=t1.Output.TeamCityUsers'
  - '*.Output.LogFile:=t1.Output.LogFile'
