apiVersion: v1alpha1
kind: rule
meta:
  name: FetchGithubOrgMembers
  purpose: Fetch GitHub organization members
  description: Fetch GitHub organization members
  labels:
    appType:
    - githubconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - githubconnector
spec:
  inputs:
    OrganizationName: 
  inputsMeta__:
  - name: OrganizationName
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: FetchGithubOrgMembers
    alias: t1
    type: task
    appTags:
      appType:
      - githubconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: Fetch GitHub organization members
    description: Fetch GitHub organization members
  ioMap:
  - t1.Input.OrganizationName:=*.Input.OrganizationName
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.GitHubOrganizationMembers:=t1.Output.GitHubOrganizationMembers'
  - '*.Output.LogFile:=t1.Output.LogFile' 
