apiVersion: v1alpha1
kind: rule
meta:
  name: AzureUsersAuthData
  purpose: Azure Users Auth Data
  description: Azure Users Auth Data
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetAzureADUsersAuthData  
    alias: t1
    type: task
    purpose: GetAzureADUsersAuthData 
    description: GetAzureADUsersAuthData
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureADUsersAuthData:=t1.Output.AzureADUsersAuthData'
  - '*.Output.LogFile:=t1.Output.LogFile'
