SQLQuery = '''
SELECT
    inputfile1.*,
    list({
        "timestamp": inputfile2.timestamp
    }) FILTER (inputfile2.timestamp IS NOT NULL)
    AS UsageLogTimestamps
FROM inputfile1
LEFT JOIN inputfile2
    ON inputfile1.email = (inputfile2.resource->>'$.labels.email_id')
GROUP BY inputfile1.*;
'''