apiVersion: v1alpha1
kind: rule
meta:
  name: ListGoogleWorkSpaceDevices
  purpose: List Google Work Space Devices
  description: List Google Work Space Devices
  labels:
    appType:
    - googleworkspaceappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - googleworkspaceappconnector
spec:
  tasks:
  - name: ListGoogleWorkSpaceDevices
    alias: t1
    type: task
    purpose: List Google Work Space Devices
    description: List Google Work Space Devices
  ioMap:
  - t1.Input.BucketName:=*.Input.BucketName
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.MobileDevicesReport:=t1.Output.MobileDevicesReport'
