authors:
- lokesh.b@continube.com
domain: continube
createdDate: 12/06/2024
name: SnykVulnerabilityReport
displayName: SnykVulnerabilityReport
version: '1.0'
description: SnykVulnerabilityReport
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: ConfigFile # A unique identifier of the task input
  description: Config File # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: SnykScanReport
  description: Snyk Scan Report
  dataType: FILE
- name: LogFile
  description: Log File
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
