authors:
- mani.m@continube.com
domain: continube
createdDate: 08/04/2024
name: ListGoogleWorkSpaceDevices
displayName: ListGoogleWorkSpaceDevices
version: '1.0'
description: ListGoogleWorkSpaceDevices
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: go
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
outputs:
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
- name: LogFile
  description: LogFile
  dataType: FILE
- name: MobileDevicesReport
  description: MobileDevicesReport
  dataType: FILE
