// This file is autogenerated. Modify as per your task needs.
package main

type UserInputs struct {
}

type Outputs struct {
	ComplianceStatus_   string
	CompliancePCT_      int
	LogFile             string
	MobileDevicesReport string
}
