[Variables]
# No variables needed for this request.

[Request]
URL = "https://logs.us-east-1.amazonaws.com/"
Method = "POST"
ContentType = "application/x-amz-json-1.1"
Redirect = true
CredentialType = "AWSSignature"
TimeOut = 30
Verify = true
MaxWorkers = 5

[Request.Retries.RetryOnCondition]
ConditionField = "{%{response.status_code}%}"
ConditionValue = "503|504|429|400"
TimeInterval = 3
MaxRetries = 3
RetryBaseDelay = 2
RetryMaxDelay = 60

[Request.Headers]
Content-Type = "application/x-amz-json-1.1"
X-Amz-Target = "Logs_20140328.StartQuery"

[Request.Params]

[Request.Data]
[Request.Data.Raw]
Value = '{"logGroupName": "{%{inputfile.LogGroupName}%}", "startTime": {%{inputfile.StartTime}%}, "endTime": {%{inputfile.EndTime}%}, "queryString": "fields @timestamp, @message, eventTime, eventSource, eventName, awsRegion, userIdentity.arn | filter eventSource = \"bedrock.amazonaws.com\" | filter eventName = \"InvokeAgent\" | sort eventTime desc"}'