authors:
- mani.m@continube.com
domain: continube
createdDate: 13/06/2024
name: ListJiraIssues
displayName: ListJiraIssues
version: '1.0'
description: ListJiraIssues
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
outputs:
- name: JiraIssueList
  description: Jira Issue List
  dataType: FILE
- name: LogFile
  description: Log File
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
