apiVersion: v1alpha1
kind: rule
meta:
  name: GetIntuneUsers
  purpose: GetIntuneUsers
  description: GetIntuneUsers
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetIntuneUsers
    alias: t1
    type: task
    purpose: GetIntuneUsers
    description: GetIntuneUsers
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.IntuneUsers:=t1.Output.IntuneUsers'
  - '*.Output.IntuneAdminUsers:=t1.Output.IntuneAdminUsers'
  - '*.Output.LogFile:=t1.Output.LogFile'
