id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: BearerToken
  displayName: BearerToken
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes:
  - name: ValidationCURL
    displayName: ValidationCURL
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: Token
    displayName: Token
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
status: null
isVersionToBeOverride: true
