apiVersion: rule.policycow.live/v1alpha1
kind: rule
meta:
  name: GCPCloudStorageLoggingEnabled
  purpose: Ensures access logging is enabled for Cloud Storage buckets to track data
    interactions, enhance security monitoring, and support compliance.
  description: Ensures access logging is enabled for Cloud Storage buckets to track data
    interactions, enhance security monitoring, and support compliance.
  labels:
    appType:
      - httprequest
    environment:
      - logical
    execlevel:
      - app
  app: HttpRequest
  annotations: {}
spec:
  inputs:
    BucketsRequestConfigFile: <<MINIO_FILE_PATH>>                   # Request Config file to get the list of buckets from GCP Cloud Storage  
    CheckIfLoggingExistConditionConfig: <<MINIO_FILE_PATH>>         # Condition config file to check if Logging Exists or not      
    OutputFileFormat: JSON
    TransformLoggingNotExistConfigFile: <<MINIO_FILE_PATH>>         # Transform config file to standardize Logging not existing file        
    MergeType: APPEND
    TransformLoggingExistConfigFile: <<MINIO_FILE_PATH>>            # Transform config file to standardize Logging existing file        
    ExtractBucketsJQExpression: .[].items[] 
  inputsMeta__:
    - name: BucketsRequestConfigFile
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: CheckIfLoggingExistConditionConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputFileFormat
      dataType: STRING
      defaultValue: JSON
      showField: true
      required: true
      allowedValues:
        - JSON
        - CSV
        - PARQUET
      repeated: false
      explanation: ''
    - name: TransformLoggingNotExistConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: MergeType
      dataType: STRING
      defaultValue: APPEND
      showField: true
      required: true
      allowedValues:
        - APPEND
        - CONCATENATE
      repeated: false
      explanation: ''
    - name: TransformLoggingExistConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: ExtractBucketsJQExpression
      dataType: JQ_EXPRESSION
      defaultValue: .[].items[]
      showField: true
      required: true
      allowedValues: []
      repeated: false
  tasks:
    - name: ExecuteHttpRequestV2
      alias: GetBucketList
      type: task
      purpose: ExecuteHttpRequestV2
      description: Executes HTTP API requests with configurable authentication, data
        handling, and response processing. Supports batch requests, flexible
        response transformation, and error management for reliable API
        integration and data collection.
      appTags:
        appType:
          - httprequest
        environment:
          - logical
        execlevel:
          - app
    - name: ExtractDataUsingJQV2
      alias: ExtractBuckets
      type: task
      purpose: ExtractDataUsingJQV2
      description: Extract and transform JSON data using JQ expressions. Supports batch
        processing with configurable chunk sizes and error handling for reliable
        processing.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: CheckConditionV2
      alias: CheckLoggingExist
      type: task
      purpose: CheckConditionV2
      description: Validates data records against configurable conditions. Splits input
        data into matched and unmatched files using criteria such as text
        patterns, number ranges, dates, or CEL expressions. Also supports field
        updates and conditional transformations to ensure compliance and data
        quality.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: TransformLoggingNotExistFile
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
        block:
          - block-4
    - name: TransformDataV2
      alias: TransformLoggingExistFile
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
        block:
          - block-4
    - name: MergeDataV2
      alias: MergingTransformedLogging
      type: task
      purpose: MergeDataV2
      description: Combine data from two input files using flexible merge strategies.
        Supports APPEND (stack rows vertically) and CONCATENATE (join columns
        horizontally by position). Handles multiple file formats with error
        handling for reliable integration.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
  ioMap:
    - GetBucketList.Input.RequestConfigFile:=*.Input.BucketsRequestConfigFile
    - ExtractBuckets.Input.InputFile:=GetBucketList.Output.OutputFile
    - ExtractBuckets.Input.JQExpression:=*.Input.ExtractBucketsJQExpression
    - ExtractBuckets.Input.LogFile:=GetBucketList.Output.LogFile
    - CheckLoggingExist.Input.InputFile:=ExtractBuckets.Output.OutputFile
    - CheckLoggingExist.Input.ConditionConfig:=*.Input.CheckIfLoggingExistConditionConfig
    - CheckLoggingExist.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - CheckLoggingExist.Input.LogFile:=ExtractBuckets.Output.LogFile
    - TransformLoggingNotExistFile.Input.InputFile1:=CheckLoggingExist.Output.UnmatchedConditionFile
    - TransformLoggingNotExistFile.Input.TransformConfigFile:=*.Input.TransformLoggingNotExistConfigFile
    - TransformLoggingNotExistFile.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformLoggingNotExistFile.Input.LogFile:=CheckLoggingExist.Output.LogFile
    - TransformLoggingExistFile.Input.InputFile1:=CheckLoggingExist.Output.MatchedConditionFile
    - TransformLoggingExistFile.Input.TransformConfigFile:=*.Input.TransformLoggingExistConfigFile
    - TransformLoggingExistFile.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformLoggingExistFile.Input.LogFile:=CheckLoggingExist.Output.LogFile
    - MergingTransformedLogging.Input.InputFile1:=TransformLoggingNotExistFile.Output.OutputFile
    - MergingTransformedLogging.Input.InputFile2:=TransformLoggingExistFile.Output.OutputFile
    - MergingTransformedLogging.Input.MergeType:=*.Input.MergeType
    - MergingTransformedLogging.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - '*.Output.CompliancePCT_:=MergingTransformedLogging.Output.CompliancePCT_'
    - '*.Output.ComplianceStatus_:=MergingTransformedLogging.Output.ComplianceStatus_'
    - '*.Output.LogFile:=MergingTransformedLogging.Output.LogFile'
    - '*.Output.GCPCloudStorageLoggingStatusReport:=MergingTransformedLogging.Output.MergedData'
