apiVersion: v1alpha1
kind: rule
meta:
  name: IntuneUserRegistrationDetails
  purpose: Generate intune user registration details
  description: Generate intune user registration details
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    appType:
    - azureappconnector
spec:
  tasks:
  - name: IntuneUserRegistrationDetails
    alias: t1
    type: task
    purpose: Generate intune user registration details
    description: Generate intune user registration details
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.IntunePrivilegedUserDetails:=t1.Output.IntunePrivilegedUserDetails'
