id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: GCPConnector
  displayName: GCPConnector
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - gcpconnector
  annotations:
    annotateType:
    - gcpconnector
spec:
  url: http://localhost.com
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidateGCPConnector
    taskVersion: ""
  credentialTypes:
  - name: GoogleWorkSpace
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: GoogleWorkSpace
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses: []
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
  hasSupportForCURLValidation: false
isVersionToBeOverride: true
