id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: NoCred
  displayName: NoCred
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes:
  - name: Dummy
    displayName: Dummy
    secret: false
    required: false
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
status: null
isVersionToBeOverride: false
