// This file is autogenerated. Modify as per your task needs.
package main

import (
	sshconnector "applicationtypes/sshconnector"
)

type UserInputs struct {
	sshconnector.SSHConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
