// This file is autogenerated. Modify as per your task needs.
package main

import (
	httprequest "applicationtypes/httprequest"
)

type UserInputs struct {
	httprequest.HttpRequest `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
