// This file is autogenerated. Modify as per your task needs.
package main

type UserInputs struct {
	Region              []string `yaml:"Region" validate:"required"`
	AWSProductName      string   `yaml:"AWSProductName" validate:"required"`
	FindingsRecordState string   `yaml:"FindingsRecordState" validate:"required"`
}

type Outputs struct {
	ErrorDetails            error
	SecurityHubFindingsFile string
	LogFile                 string
	CompliancePCT_          int
	ComplianceStatus_       string
}
