// This file is autogenerated. Modify as per your task needs.
package main

import (
	gcpconnector "applicationtypes/gcpconnector"
)

type UserInputs struct {
	gcpconnector.GCPConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
