authors:
- rufus.p@continube.com
domain: continube
createdDate: 14/05/2024
name: EnsureAdministrativeSessionTimeoutIsLTTwoHrs
displayName: EnsureAdministrativeSessionTimeoutIsLTTwoHrs
version: '1.0'
description: EnsureAdministrativeSessionTimeoutIsLTTwoHrs
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: PoliciesData # A unique identifier of the task input
  description: PoliciesData # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: AdminUsersData # A unique identifier of the task input
  description: AdminUsersData # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: AllowedSessionLifetimeMinutes # A unique identifier of the task input
  description: AllowedSessionLifetimeMinutes # A concise description of the task input
  dataType: INT
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: AdministrativeSessionTimeoutReport
  description: AdministrativeSessionTimeoutReport
  dataType: FILE
- name: Policies
  description: Policies
  dataType: FILE
- name: CompliantPolicies
  description: CompliantPolicies
  dataType: FILE
- name: AdminUsers
  description: AdminUsers
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
