id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: Azure
  displayName: Azure
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes:
  - name: clientID
    displayName: ClientID
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: clientSecret
    displayName: ClientSecret
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: tenantID
    displayName: TenantID
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: subscriptionID
    displayName: SubscriptionID
    secret: false
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
status: null
isVersionToBeOverride: true
