authors:
- mani.m@continube.com
domain: continube
createdDate: 09/07/2024
name: AWSCloudTrailEvents
displayName: AWSCloudTrailEventsofIAMUsers
version: '1.0'
description: AWSCloudTrailEventsofIAMUsers
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: Region # A unique identifier of the task input
  description: Region # A concise description of the task input
  dataType: STRING
  repeated: true
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: EventFile # A unique identifier of the task input
  description: EventFile # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: ResourceFile # A unique identifier of the task input
  description: ResourceFile # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: AWSEventDetails
  description: AWS Event Details
  dataType: FILE
- name: AWSResourceDetails
  description: AWS Resource Details
  dataType: FILE
- name: LogFile
  description: Log File
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
