id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: AWSSignature
  displayName: AWSSignature
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes:
  - name: ValidationCURL
    displayName: ValidationCURL
    secret: false
    required: false
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: AccessKey
    displayName: AccessKey
    secret: true
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
  - name: SecretKey
    displayName: SecretKey
    secret: true
    required: true
    multiSelect: false
    dataType: STRING
    allowedValues: []
    defaultValue: ""
status: null
isVersionToBeOverride: true
