id: ""
apiVersion: v1alpha1
kind: credentialType
meta:
  name: NoAuth
  displayName: NoAuth
  shortDescription: ""
  longDescription: ""
  labels: {}
  annotations: {}
  version: 1.1.1
spec:
  attributes: []
status: null
isVersionToBeOverride: false
