// This file is autogenerated. Modify as per your task needs.
package main

import (
	semgrepconnector "appconnections/semgrepconnector"
)

type UserInputs struct {
	semgrepconnector.SemgrepConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
    ValidationMessage string
}

