userObject:
  app:
    name: Kubernetes
    appPort: "0"
    appTags:
      appType:
      - kubernetes
      environment:
      - logical
      execlevel:
      - app
    appURL: "$INSTANCE_LOGIN_URL"
    userDefinedCredentials:
      Jumphost:
        SshPrivateKey: "$INSTANCE_SSH_PRIVATE_KEY"
        UserID: "$INSTANCE_USER_NAME"
userInputs:
  IncludeCriteria: ""
  ExcludeCriteria:  ""
  OpaConfigurationFile: <<MINIO_FILE_PATH>>
fromDate: 2023-11-24T06:03:00Z
toDate: 2023-11-24T06:03:00Z