id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: GoogleWorkSpaceAppConnector
  displayName: GoogleWorkSpaceAppConnector
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - googleworkspaceappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - googleworkspaceappconnector
spec:
  url: https://accounts.google.com
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidateGoogleWorkSpaceAppConnector
    taskVersion: ""
  credentialTypes:
  - name: GoogleWorkSpace
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: GoogleWorkSpace
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses: []
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
isVersionToBeOverride: true
