[AddColumn]
"System" = "github"
"Source" = "compliancecow"
"ResourceID" = "N/A"
"ResourceName" = "<<inputfile1.account_owner>>/<<inputfile1.repository_name>>"
"ResourceType" = "Repository"
"ResourceLocation" = "<<inputfile1.most_recent_instance.location.path>>"
"ResourceTags" = "N/A"
"ResourceURL" = "<<inputfile1.html_url>>"
"VulnerabilityAlertNumber" = "<<inputfile1.number>>"
"VulnerabilityDescription" = "<<inputfile1.most_recent_instance.message.text>>"
"VulnerabilityStartLine" = "<<inputfile1.most_recent_instance.location.start_line>>"
"VulnerabilityEndLine" = "<<inputfile1.most_recent_instance.location.end_line>>"
"Tool" = "<<inputfile1.tool.name>>"
"RuleID" = "<<inputfile1.rule.id>>"
"RuleDescription" = "<<inputfile1.rule.description>>"
"RuleDetailedDescription" = "<<inputfile1.rule.full_description>>"
"State" = "<<inputfile1.state>>"
"FixedAt" = "<<inputfile1.fixed_at>>"
"DismissedBy" = "<<inputfile1.dismissed_by.login>>"
"DismissedAt" = "<<inputfile1.dismissed_at>>"
"DismissedReason" = "<<inputfile1.dismissed_reason>>"
"DismissedComment" = "<<inputfile1.dismissed_comment>>"
"Severity" = "<<inputfile1.rule.security_severity_level>>"
"Recommendation" = "<<inputfile1.rule.help>>"
"ValidationStatusCode" = "<<inputfile1.validation_status_code>>"
"ValidationStatusNotes" = "<<inputfile1.validation_status_notes>>"
"ComplianceStatus" = "<<inputfile1.compliance_status>>"
"ComplianceStatusReason" = "<<inputfile1.compliance_status_reason>>"
"EvaluatedTime" = "<<inputfile1.updated_at>>"
"UserAction" = ""
"ActionStatus" = ""
"ActionResponseURL" = ""
[ReorderColumn]
"ColumnList" = "System,Source,ResourceID,ResourceName,ResourceType,ResourceLocation,ResourceTags,ResourceURL,VulnerabilityAlertNumber,VulnerabilityDescription,VulnerabilityStartLine,VulnerabilityEndLine,Tool,RuleID,RuleDescription,RuleDetailedDescription,State,FixedAt,DismissedBy,DismissedAt,DismissedReason,DismissedComment,Severity,Recommendation,ValidationStatusCode,ValidationStatusNotes,ComplianceStatus,ComplianceStatusReason,EvaluatedTime,UserAction,ActionStatus,ActionResponseURL"