apiVersion: v1alpha1
kind: rule
meta:
  name: IntunePrivilegedUsersReAuthReport
  purpose: Intune Privileged Users ReAuth Report
  description: Intune Privileged Users ReAuth Report
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    appType:
    - azureappconnector
spec:
  inputs:
    AllowedSignInRiskLevels:
    IntuneConditionalAccessPolicies: <<MINIO_FILE_PATH>>
    IntuneUserRegistrationDetails: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: AllowedSignInRiskLevels
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: IntuneConditionalAccessPolicies
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: IntuneUserRegistrationDetails
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: IntunePrivilegedUsersReAuthReport
    alias: t1
    type: task
    purpose: Intune Privileged Users ReAuth Report
    description: Intune Privileged Users ReAuth Report
  ioMap:
  - 't1.Input.AllowedSignInRiskLevels:=*.Input.AllowedSignInRiskLevels'
  - 't1.Input.IntuneConditionalAccessPolicies:=*.Input.IntuneConditionalAccessPolicies'
  - 't1.Input.IntuneUserRegistrationDetails:=*.Input.IntuneUserRegistrationDetails'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.IntunePrivilegedReAuthReport:=t1.Output.IntunePrivilegedReAuthReport'
