// This file is autogenerated. Modify as per your task needs.
package main

import (
	privacybisonconnector "appconnections/privacybisonconnector"
)

type UserInputs struct {
	privacybisonconnector.PrivacyBisonConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
    ValidationMessage string
}

