authors:
- mani.m@continube.com
domain: continube
createdDate: 28/03/2024
name: GenerateGoogleWorkSpaceTwoSVReport
displayName: GenerateGoogleWorkSpaceTwoSVReport
version: '1.0'
description: GenerateGoogleWorkSpaceTwoSVReport
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: GoogleWorkSpaceUsersListFile # A unique identifier of the task input
  description: GoogleWorkSpaceUsersListFile # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: EnforcePhishingResistantMFA
  description: EnforcePhishingResistantMFA
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
