// This file is autogenerated. Modify as per your task needs.
package main

type UserInputs struct {
	GoogleWorkSpaceUsersListFile string `yaml:"GoogleWorkSpaceUsersListFile" validate:"required"`
}

type Outputs struct {
	LogFile                     string
	EnforcePhishingResistantMFA string
}
