// This file is autogenerated. Modify as per your task needs.
package main

import (
	oktaconnector "applicationtypes/oktaconnector"
)

type UserInputs struct {
	oktaconnector.OktaConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
