userObject:
  app:
    name: NoCredApp
    appURL: http://localhost.com
    appPort: "0"
    userDefinedCredentials:
      NoCred:
        Dummy: ""
userInputs:
  DataFile: "<<MINIO_FILE_PATH>>"
  ExtractPath:   # array -> "0.items.0.dataItem" object -> ""data.items.dataItem""
  LogFile: "<<MINIO_FILE_PATH>>"

fromDate: 2024-09-11s
toDate: 2024-09-11
