apiVersion: rule.policycow.live/v1alpha1
kind: rule
meta:
  name: FetchAScendEngagementRequests
  purpose: >-
    Fetch engagement requests from A-SCEND by A-LIGN.
  description: >-
    Fetches engagement data from A-SCEND API, retrieves requests for each engagement, maps assignees based on category/class/type/request.
  labels:
    appType:
      - httprequest
    environment:
      - logical
    execlevel:
      - app
  tags:
    - MCP    
  annotations:
    annotateType:
      - httprequest
  app: HttpRequest
spec:
  inputs:
    EngagementsRequestConfig: <<MINIO_FILE_URL>>
    EngagementsResponseConfig: <<MINIO_FILE_URL>>
    InScopeEngagements: <<MINIO_FILE_URL>>
    RequestsSearchRequestConfig: <<MINIO_FILE_URL>>
    RequestsSearchResponseConfig: <<MINIO_FILE_URL>>
    RequestAssigneeMapping: <<MINIO_FILE_URL>>
    AssigneeMappingSQLConfig: <<MINIO_FILE_URL>>
    OutputFileFormat: JSON
    StandardizeRequestsJQConfig: <<MINIO_FILE_URL>>
    AssigneeMappingLogConfig: <<MINIO_FILE_URL>>
    ProceedOnSQLError: false
  inputsMeta__:
    - name: EngagementsRequestConfig
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: EngagementsResponseConfig
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: InScopeEngagements
      dataType: FILE
      defaultValue: <<MINIO_FILE_URL>>
      format: json
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: RequestsSearchRequestConfig
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: RequestsSearchResponseConfig
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: RequestAssigneeMapping
      dataType: FILE
      defaultValue: <<MINIO_FILE_URL>>
      format: json
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: AssigneeMappingSQLConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputFileFormat
      dataType: STRING
      defaultValue: JSON
      showField: true
      required: true
      allowedValues:
        - JSON
        - CSV
        - PARQUET
        - YAML
        - TOML
        - XLSX
      repeated: false
      explanation: ''
    - name: StandardizeRequestsJQConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: AssigneeMappingLogConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_URL>>
      format: toml
      showField: true
      required: false
      allowedValues: []
      repeated: false
    - name: ProceedOnSQLError
      dataType: BOOLEAN
      defaultValue: false
      showField: true
      required: true
      allowedValues: []
      repeated: false
  tasks:
    - name: ExecuteHttpRequestV2
      alias: FetchEngagements
      type: task
      purpose: ExecuteHttpRequestV2
      description: Detailed info about the task
      appTags:
        appType:
          - httprequest
        environment:
          - logical
        execlevel:
          - app
    - name: ExecuteHttpRequestV2
      alias: FetchRequests
      type: task
      purpose: ExecuteHttpRequestV2
      description: Detailed info about the task
      appTags:
        appType:
          - httprequest
        environment:
          - logical
        execlevel:
          - app
    - name: ExecuteSqlQueryV2
      alias: AddAssigneeMapping
      type: task
      purpose: ExecuteSqlQueryV2
      description: Detailed info about the task
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: ConvertFileFormatV2
      alias: Convert Output to JSON
      type: task
      purpose: ConvertFileFormatV2
      description: >-
        Converts data files between supported formats: JSON, CSV, PARQUET, YAML,
        TOML, XLSX, and XML. Automatically detects formats, preserves data
        structure, and ensures compatibility for flexible integration.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: ExtractDataUsingJQV2
      alias: StandardizeOutput
      type: task
      purpose: ExtractDataUsingJQV2
      description: >-
        Extract and transform JSON data using JQ expressions. Supports batch
        processing with configurable chunk sizes and error handling for reliable
        processing.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
  ioMap:
    - FetchEngagements.Input.RequestConfigFile:=*.Input.EngagementsRequestConfig
    - >-
      FetchEngagements.Input.ResponseConfigFile:=*.Input.EngagementsResponseConfig
    - FetchEngagements.Input.InputFile:=*.Input.InScopeEngagements
    - FetchRequests.Input.RequestConfigFile:=*.Input.RequestsSearchRequestConfig
    - >-
      FetchRequests.Input.ResponseConfigFile:=*.Input.RequestsSearchResponseConfig
    - FetchRequests.Input.InputFile:=FetchEngagements.Output.OutputFile
    - AddAssigneeMapping.Input.InputFile1:=FetchRequests.Output.OutputFile
    - AddAssigneeMapping.Input.InputFile2:=*.Input.RequestAssigneeMapping
    - AddAssigneeMapping.Input.SQLConfig:=*.Input.AssigneeMappingSQLConfig
    - AddAssigneeMapping.Input.LogConfigFile:=*.Input.AssigneeMappingLogConfig
    - AddAssigneeMapping.Input.ProceedIfErrorExists:=*.Input.ProceedOnSQLError
    - >-
      Convert Output to
      JSON.Input.InputFile:=AddAssigneeMapping.Output.OutputFile
    - Convert Output to JSON.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - Convert Output to JSON.Input.LogFile:=AddAssigneeMapping.Output.LogFile
    - >-
      StandardizeOutput.Input.InputFile:=Convert Output to
      JSON.Output.OutputFile
    - StandardizeOutput.Input.JQConfigFile:=*.Input.StandardizeRequestsJQConfig
    - StandardizeOutput.Input.LogFile:=Convert Output to JSON.Output.LogFile
    - '*.Output.CompliancePCT_:=StandardizeOutput.Output.CompliancePCT_'
    - '*.Output.ComplianceStatus_:=StandardizeOutput.Output.ComplianceStatus_'
    - '*.Output.LogFile:=StandardizeOutput.Output.LogFile'
    - '*.Output.AscendEngagementRequestsList:=StandardizeOutput.Output.OutputFile'
