apiVersion: v1alpha1
kind: rule
meta:
  name: AWSIAMStaleUsersReport
  purpose: Fetch AWS IAM users using ListUsers API and identify stale users who haven't
    used their password in more than 90 days
  description: 'This rule fetches AWS IAM users via REST API, filters for users with
    password last used date older than 90 days, transforms the data to ComplianceCow'
  labels:
    appType:
    - httprequest
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - httprequest
  tags:
    - MCP
spec:
  inputs:
    JQFilter: .[].ListUsersResponse.ListUsersResult.Users.member[] | select(.PasswordLastUsed
      == null or ((now - (.PasswordLastUsed | fromdateiso8601)) / 86400) > 90)
    JQTransform: 'map(  . as $user |  ($user.PasswordLastUsed // null) as $lastUsed
      |  (if $lastUsed == null then null else (now - ($lastUsed | fromdateiso8601))
      / 86400 | floor end) as $daysSince |  {    System: "aws",    Source: "compliancecow",     ResourceID:
      $user.Arn,    ResourceName: $user.UserName,    ResourceType: "User",    ResourceLocation:
      ($user.Arn | split(":")[3]),    ResourceTags: ($user.Tags // []),    UserName:
      $user.UserName,    PasswordLastUsed: $lastUsed,    DaysSinceLastUsed: $daysSince,    IsStale:
      ($lastUsed == null or $daysSince > 90),    ValidationStatusCode: (if ($lastUsed
      == null or $daysSince > 90) then "PASS_ACCT_STALE" else "FAIL_ACCT_ACTV" end),    ValidationStatusNotes:
      (if $lastUsed == null then "User has never used password - considered stale"
      elif $daysSince > 90 then "Password last used \($daysSince) days ago - exceeds
      90 day threshold" else "Password used within 90 days - account active" end),    ComplianceStatus:
      (if ($lastUsed == null or $daysSince > 90) then "NON_COMPLIANT" else "COMPLIANT"
      end),    ComplianceStatusReason: (if ($lastUsed == null or $daysSince > 90)
      then "Stale user account detected - password not used in over 90 days" else
      "Active user account - password used within compliance period" end),    EvaluatedTime:
      (now | strftime("%Y-%m-%dT%H:%M:%SZ")),    UserAction: "",    ActionStatus:
      "",    ActionResponseURL: ""  })|.[]'
    OutputFileFormat: CSV
    OutputMethod: ALL
    RequestConfigFile: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: RequestConfigFile
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: JQTransform
    dataType: JQ_EXPRESSION
    repeated: false
    defaultValue: 'map(  . as $user |  ($user.PasswordLastUsed // null) as $lastUsed
      |  (if $lastUsed == null then null else (now - ($lastUsed | fromdateiso8601))
      / 86400 | floor end) as $daysSince |  {    System: "aws",    Source: "compliancecow",     ResourceID:
      $user.Arn,    ResourceName: $user.UserName,    ResourceType: "User",    ResourceLocation:
      ($user.Arn | split(":")[3]),    ResourceTags: ($user.Tags // []),    UserName:
      $user.UserName,    PasswordLastUsed: $lastUsed,    DaysSinceLastUsed: $daysSince,    IsStale:
      ($lastUsed == null or $daysSince > 90),    ValidationStatusCode: (if ($lastUsed
      == null or $daysSince > 90) then "PASS_ACCT_STALE" else "FAIL_ACCT_ACTV" end),    ValidationStatusNotes:
      (if $lastUsed == null then "User has never used password - considered stale"
      elif $daysSince > 90 then "Password last used \($daysSince) days ago - exceeds
      90 day threshold" else "Password used within 90 days - account active" end),    ComplianceStatus:
      (if ($lastUsed == null or $daysSince > 90) then "NON_COMPLIANT" else "COMPLIANT"
      end),    ComplianceStatusReason: (if ($lastUsed == null or $daysSince > 90)
      then "Stale user account detected - password not used in over 90 days" else
      "Active user account - password used within compliance period" end),    EvaluatedTime:
      (now | strftime("%Y-%m-%dT%H:%M:%SZ")),    UserAction: "",    ActionStatus:
      "",    ActionResponseURL: ""  })|.[]'
    allowedValues: []
    showField: true
    required: true
  - name: OutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: CSV
    allowedValues: []
    showField: true
    required: true
  - name: JQFilter
    dataType: JQ_EXPRESSION
    repeated: false
    defaultValue: .[].ListUsersResponse.ListUsersResult.Users.member[] | select(.PasswordLastUsed
      == null or ((now - (.PasswordLastUsed | fromdateiso8601)) / 86400) > 90)
    allowedValues: []
    showField: true
    required: true
  - name: OutputMethod
    dataType: STRING
    repeated: false
    defaultValue: ALL
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: ExecuteHttpRequestV2
    alias: Fetch List of All AWS IAM Users
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    purpose: Fetch the list of all AWS IAM users using ListUsers API
    description: Executes HTTP API requests with configurable authentication, data
      handling, and response processing. Supports batch requests, flexible response
      transformation, and error management for reliable API integration and data collection.
  - name: FilterDataWithJQ
    alias: Filter Stale IAM Users
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Filter users who haven't used their password in over 90 days or never
      used it
    description: Filter data records using JQ expressions to extract only records that match
      specified criteria. Apply flexible query conditions to identify compliant records,
      active users, high-priority items, or any subset based on business rules.
  - name: TransformDataWithJQ
    alias: Standardize Stale IAM User Data
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Standardize the stale IAM user data
    description: >-
        Transform and modify data records using JQ expressions. Add new columns,
        rename fields, perform calculations, and restructure data using JQ's
        powerful transformation capabilities.
  - name: ConvertFileFormatV2
    alias: Convert Final Output to CSV Format
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Convert the final output to CSV format
    description: 'Convert files between the supported formats: JSON, CSV, PARQUET,
      YAML, TOML, and XLSX.'
  ioMap:
  - Fetch List of All AWS IAM Users.Input.RequestConfigFile:=*.Input.RequestConfigFile
  - Filter Stale IAM Users.Input.InputFile:=Fetch List of All AWS IAM Users.Output.OutputFile
  - Filter Stale IAM Users.Input.JQFilter:=*.Input.JQFilter
  - Filter Stale IAM Users.Input.OutputMethod:=*.Input.OutputMethod
  - Filter Stale IAM Users.Input.LogFile:=Fetch List of All AWS IAM Users.Output.LogFile
  - Standardize Stale IAM User Data.Input.InputFile:=Filter Stale IAM Users.Output.FilteredFile
  - Standardize Stale IAM User Data.Input.JQTransform:=*.Input.JQTransform
  - Standardize Stale IAM User Data.Input.OutputMethod:=*.Input.OutputMethod
  - Standardize Stale IAM User Data.Input.LogFile:=Filter Stale IAM Users.Output.LogFile
  - Convert Final Output to CSV Format.Input.InputFile:=Standardize Stale IAM User
    Data.Output.TransformedFile
  - Convert Final Output to CSV Format.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - Convert Final Output to CSV Format.Input.LogFile:=Standardize Stale IAM User Data.Output.LogFile
  - '*.Output.CompliancePCT_:=Convert Final Output to CSV Format.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=Convert Final Output to CSV Format.Output.ComplianceStatus_'
  - '*.Output.LogFile:=Convert Final Output to CSV Format.Output.LogFile'
  - '*.Output.StaleUsersReport:=Convert Final Output to CSV Format.Output.OutputFile'
