apiVersion: v1alpha1
kind: rule
meta:
  name: FetchGitHubCodeScanningAlerts
  purpose: Fetch GitHub repository code scanning alerts
  description: Fetch GitHub repository code scanning alerts
  labels:
    appType:
    - httprequest
    environment:
    - logical
    execlevel:
    - app
    provider:
    - github
spec:
  inputs:
    GitHubCodeScanningConditionConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningInputFile: <<MINIO_FILE_PATH>>
    OutputFileFormat: JSON
    GitHubCodeScanningRequestConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningResponseConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningTransformConfig: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: GitHubCodeScanningInputFile
    dataType: FILE
    repeated: false
    format: json
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningResponseConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningRequestConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningConditionConfig
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: OutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: JSON
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningTransformConfig
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: ExecuteHttpRequest
    alias: FetchGitHubCodeScanningAlerts
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
      provider:
      - github
    purpose: List the details of GitHub repository code scanning alerts.
    description: List the details of GitHub repository code scanning alerts.
  - name: CheckCondition
    alias: FilterCodeScanningAlerts
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Filter the GitHub code scanning alerts by vulnerability state (open,
      fixed, dismissed) and severity (low, medium, high, critical)
    description: Filter the GitHub code scanning alerts by vulnerability state (open,
      fixed, dismissed) and severity (low, medium, high, critical)
  - name: ConvertFileFormat
    alias: ConvertJsonFromParquet
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Convert files between the supported formats - (JSON, CSV, YAML, TOML,
      PARQUET)
    description: Convert files between the supported formats - (JSON, CSV, YAML, TOML,
      PARQUET)
  - name: TransformData
    alias: CreateCCowStandardFormat
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Convert GitHub code scanning alerts into the ComplianceCow standard
      structure
    description: Convert GitHub code scanning alerts into the ComplianceCow standard
      structure
  ioMap:
  - FetchGitHubCodeScanningAlerts.Input.RequestConfigFile:=*.Input.GitHubCodeScanningRequestConfig
  - FetchGitHubCodeScanningAlerts.Input.ResponseConfigFile:=*.Input.GitHubCodeScanningResponseConfig
  - FetchGitHubCodeScanningAlerts.Input.InputFile:=*.Input.GitHubCodeScanningInputFile
  - FilterCodeScanningAlerts.Input.InputFile:=FetchGitHubCodeScanningAlerts.Output.OutputFile
  - FilterCodeScanningAlerts.Input.ConditionConfig:=*.Input.GitHubCodeScanningConditionConfig
  - FilterCodeScanningAlerts.Input.LogFile:=FetchGitHubCodeScanningAlerts.Output.LogFile
  - ConvertJsonFromParquet.Input.InputFile:=FilterCodeScanningAlerts.Output.MatchedConditionFile
  - ConvertJsonFromParquet.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - ConvertJsonFromParquet.Input.LogFile:=FilterCodeScanningAlerts.Output.LogFile
  - CreateCCowStandardFormat.Input.InputFile1:=ConvertJsonFromParquet.Output.OutputFile
  - CreateCCowStandardFormat.Input.TransformConfigFile:=*.Input.GitHubCodeScanningTransformConfig
  - CreateCCowStandardFormat.Input.LogFile:=ConvertJsonFromParquet.Output.LogFile
  - '*.Output.CompliancePCT_:=CreateCCowStandardFormat.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=CreateCCowStandardFormat.Output.ComplianceStatus_'
  - '*.Output.LogFile:=CreateCCowStandardFormat.Output.LogFile'
  - '*.Output.GitHubCodeScanningAlertsReport:=CreateCCowStandardFormat.Output.OutputFile'
