apiVersion: v1alpha1
kind: rule
meta:
  name: FetchGitHubCodeScanningAlerts
  purpose: Fetch GitHub repository code scanning alerts
  description: Fetch GitHub repository code scanning alerts
  labels:
    appType:
    - httprequest
    environment:
    - logical
    execlevel:
    - app
    provider:
    - github
spec:
  inputs:
    GitHubCodeScanningConditionConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningInputFile: <<MINIO_FILE_PATH>>
    OutputFileFormat: JSON
    GitHubCodeScanningRequestConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningResponseConfig: <<MINIO_FILE_PATH>>
    GitHubCodeScanningTransformConfig: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: GitHubCodeScanningInputFile
    dataType: FILE
    repeated: false
    format: json
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningResponseConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningRequestConfig
    dataType: HTTP_CONFIG
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: GitHubCodeScanningConditionConfig
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: OutputFileFormat
    dataType: STRING
    repeated: false
    defaultValue: JSON
    allowedValues:
    - JSON
    - CSV
    - PARQUET
    showField: true
    required: true
  - name: GitHubCodeScanningTransformConfig
    dataType: FILE
    repeated: false
    format: toml
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: ExecuteHttpRequestV2
    alias: FetchGitHubCodeScanningAlerts
    type: task
    appTags:
      appType:
      - httprequest
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Executes HTTP API requests with configurable authentication, data
      handling, and response processing. Supports batch requests, flexible response
      transformation, and error management for reliable API integration and data collection.
  - name: CheckConditionV2
    alias: FilterCodeScanningAlerts
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Validates data records against configurable conditions. Splits input
      data into matched and unmatched files using criteria such as text patterns,
      number ranges, dates, or CEL expressions. Also supports field updates and conditional
      transformations to ensure compliance and data quality.
  - name: TransformDataV2
    alias: CreateCCowStandardFormat
    type: task
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    purpose: Purpose of the task
    description: Transform and manipulate data columns by adding, updating, deleting,
      reordering, or deduplicating fields. Supports conditional logic, cross-file
      data mapping, function-based calculations, and complex restructuring for compliance
      and reporting.
  ioMap:
  - FetchGitHubCodeScanningAlerts.Input.RequestConfigFile:=*.Input.GitHubCodeScanningRequestConfig
  - FetchGitHubCodeScanningAlerts.Input.ResponseConfigFile:=*.Input.GitHubCodeScanningResponseConfig
  - FetchGitHubCodeScanningAlerts.Input.InputFile:=*.Input.GitHubCodeScanningInputFile
  - FilterCodeScanningAlerts.Input.InputFile:=FetchGitHubCodeScanningAlerts.Output.OutputFile
  - FilterCodeScanningAlerts.Input.ConditionConfig:=*.Input.GitHubCodeScanningConditionConfig
  - FilterCodeScanningAlerts.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - FilterCodeScanningAlerts.Input.LogFile:=FetchGitHubCodeScanningAlerts.Output.LogFile
  - CreateCCowStandardFormat.Input.InputFile1:=FilterCodeScanningAlerts.Output.MatchedConditionFile
  - CreateCCowStandardFormat.Input.TransformConfigFile:=*.Input.GitHubCodeScanningTransformConfig
  - CreateCCowStandardFormat.Input.OutputFileFormat:=*.Input.OutputFileFormat
  - CreateCCowStandardFormat.Input.LogFile:=FilterCodeScanningAlerts.Output.LogFile
  - '*.Output.CompliancePCT_:=CreateCCowStandardFormat.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=CreateCCowStandardFormat.Output.ComplianceStatus_'
  - '*.Output.LogFile:=CreateCCowStandardFormat.Output.LogFile'
  - '*.Output.GitHubCodeScanningAlertsReport:=CreateCCowStandardFormat.Output.OutputFile'
