apiVersion: v1alpha1
kind: rule
meta:
  name: FetchSemgrepFindings
  purpose: To fetch, process, and summarize vulnerability findings from Semgrep, generating separate reports for code vulnerabilities and supply chain vulnerabilities based on specific criteria.
  description: This task interacts with the Semgrep API to retrieve deployment details, validate and filter projects, list findings based on severity, and format them into structured data. It generates and uploads detailed reports for both code and supply chain vulnerabilities, ensuring compliance status and validation information is clearly documented.
  labels:
    appType:
    - semgrepconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - semgrepconnector
spec:
  inputs:
    IncludeCriteria: 
    ExcludeCriteria: 
    Severity: 
  inputsMeta__:
  - name: IncludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  - name: ExcludeCriteria
    dataType: STRING
    repeated: false
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  - name: Severity
    dataType: STRING
    repeated: true
    defaultValue: 
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: FetchSemgrepFindings
    alias: t1
    type: task
    purpose: To fetch, process, and summarize vulnerability findings from Semgrep, generating separate reports for code vulnerabilities and supply chain vulnerabilities based on specific criteria.
    description: This task interacts with the Semgrep API to retrieve deployment details, validate and filter projects, list findings based on severity, and format them into structured data. It generates and uploads detailed reports for both code and supply chain vulnerabilities, ensuring compliance status and validation information is clearly documented.
  ioMap:
  - 't1.Input.IncludeCriteria:=*.Input.IncludeCriteria'
  - 't1.Input.ExcludeCriteria:=*.Input.ExcludeCriteria'
  - 't1.Input.Severity:=*.Input.Severity'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.SemgrepCodeVulnerabilityReport:=t1.Output.SemgrepCodeVulnerabilityReport'
  - '*.Output.SemgrepSupplyChainVulnerabilityReport:=t1.Output.SemgrepSupplyChainVulnerabilityReport'
  - '*.Output.SemgrepCodeFindingsSummaryReport:=t1.Output.SemgrepCodeFindingsSummaryReport'
  - '*.Output.SemgrepSupplyChainFindingsSummaryReport:=t1.Output.SemgrepSupplyChainFindingsSummaryReport'
  # - '*.Output.SemgrepSecretsVulnerabilityReport:=t1.Output.SemgrepSecretsVulnerabilityReport'
