// This file is autogenerated. Modify as per your task needs.
package main

import (
	awsappconnector "appconnections/awsappconnector"
)

type UserInputs struct {
	awsappconnector.AWSAppConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
