// This file is autogenerated. Modify as per your task needs.
package main

type UserInputs struct {
	MobileDevicesReport string `yaml:"MobileDevicesReport" validate:"required"`
}

type Outputs struct {
	ComplianceStatus_                  string
	CompliancePCT_                     int
	LogFile                            string
	GoogleWorkSpaceManagedDeviceReport string
}
