apiVersion: rule.policycow.live/v1alpha1
kind: rule
meta:
  name: GCPCloudStorageVersioningEnabled
  purpose: This rule ensures that object versioning is enabled for all Cloud Storage
    buckets in the specified Google Cloud project.
  description: This rule ensures that object versioning is enabled for all Cloud Storage
    buckets in the specified Google Cloud project.
  labels:
    appType:
      - httprequest
    environment:
      - logical
    execlevel:
      - app
  app: HttpRequest
  annotations: {}
spec:
  inputs:
    BucketsRequestConfigFile: <<MINIO_FILE_PATH>>
    OutputMethod: ALL
    CheckIfVersioningExistsConditionConfig: <<MINIO_FILE_PATH>>
    OutputFileFormat: JSON
    TransformVersioningNotExistConfigFile: <<MINIO_FILE_PATH>>
    TransformVersioningExistConfigFile: <<MINIO_FILE_PATH>>
    MergeType: APPEND
    ExtractBucketsJQExpression: .[].items[]
  inputsMeta__:
    - name: BucketsRequestConfigFile
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputMethod
      dataType: STRING
      defaultValue: ALL
      showField: true
      required: true
      allowedValues:
        - FIRST
        - ALL
      repeated: false
      explanation: ''
    - name: CheckIfVersioningExistsConditionConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputFileFormat
      dataType: STRING
      defaultValue: JSON
      showField: true
      required: true
      allowedValues:
        - JSON
        - CSV
        - PARQUET
      repeated: false
      explanation: ''
    - name: TransformVersioningNotExistConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: TransformVersioningExistConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: MergeType
      dataType: STRING
      defaultValue: APPEND
      showField: true
      required: true
      allowedValues:
        - APPEND
        - CONCATENATE
      repeated: false
      explanation: ''
    - name: ExtractBucketsJQExpression
      dataType: JQ_EXPRESSION
      defaultValue: .[].items[]
      showField: true
      required: true
      allowedValues: []
      repeated: false
  tasks:
    - name: ExecuteHttpRequestV2
      alias: GetBucketsList
      type: task
      purpose: ExecuteHttpRequestV2
      description: Executes HTTP API requests with configurable authentication, data
        handling, and response processing. Supports batch requests, flexible
        response transformation, and error management for reliable API
        integration and data collection.
      appTags:
        appType:
          - httprequest
        environment:
          - logical
        execlevel:
          - app
    - name: ExtractDataUsingJQV2
      alias: ExtractBuckets
      type: task
      purpose: ExtractDataUsingJQV2
      description: Extract and transform JSON data using JQ expressions. Supports batch
        processing with configurable chunk sizes and error handling for reliable
        processing.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: CheckConditionV2
      alias: CheckIfVersioningExists
      type: task
      purpose: CheckConditionV2
      description: Validates data records against configurable conditions. Splits input
        data into matched and unmatched files using criteria such as text
        patterns, number ranges, dates, or CEL expressions. Also supports field
        updates and conditional transformations to ensure compliance and data
        quality.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: TransformVersioningNotExistFile
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
        block:
          - block-4
    - name: TransformDataV2
      alias: TransformVersioningExistFile
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
        block:
          - block-4
    - name: MergeDataV2
      alias: MergeVersioningExistAndNotExistFile
      type: task
      purpose: MergeDataV2
      description: Combine data from two input files using flexible merge strategies.
        Supports APPEND (stack rows vertically) and CONCATENATE (join columns
        horizontally by position). Handles multiple file formats with error
        handling for reliable integration.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
  ioMap:
    - GetBucketsList.Input.RequestConfigFile:=*.Input.BucketsRequestConfigFile
    - ExtractBuckets.Input.InputFile:=GetBucketsList.Output.OutputFile
    - ExtractBuckets.Input.JQExpression:=*.Input.ExtractBucketsJQExpression
    - ExtractBuckets.Input.LogFile:=GetBucketsList.Output.LogFile
    - CheckIfVersioningExists.Input.InputFile:=ExtractBuckets.Output.OutputFile
    - CheckIfVersioningExists.Input.ConditionConfig:=*.Input.CheckIfVersioningExistsConditionConfig
    - CheckIfVersioningExists.Input.LogFile:=ExtractBuckets.Output.LogFile
    - TransformVersioningNotExistFile.Input.InputFile1:=CheckIfVersioningExists.Output.UnmatchedConditionFile
    - TransformVersioningNotExistFile.Input.TransformConfigFile:=*.Input.TransformVersioningNotExistConfigFile
    - TransformVersioningNotExistFile.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformVersioningNotExistFile.Input.LogFile:=CheckIfVersioningExists.Output.LogFile
    - TransformVersioningExistFile.Input.InputFile1:=CheckIfVersioningExists.Output.MatchedConditionFile
    - TransformVersioningExistFile.Input.TransformConfigFile:=*.Input.TransformVersioningExistConfigFile
    - TransformVersioningExistFile.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformVersioningExistFile.Input.LogFile:=CheckIfVersioningExists.Output.LogFile
    - MergeVersioningExistAndNotExistFile.Input.InputFile1:=TransformVersioningNotExistFile.Output.OutputFile
    - MergeVersioningExistAndNotExistFile.Input.InputFile2:=TransformVersioningExistFile.Output.OutputFile
    - MergeVersioningExistAndNotExistFile.Input.MergeType:=*.Input.MergeType
    - MergeVersioningExistAndNotExistFile.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - '*.Output.CompliancePCT_:=MergeVersioningExistAndNotExistFile.Output.CompliancePCT_'
    - '*.Output.ComplianceStatus_:=MergeVersioningExistAndNotExistFile.Output.ComplianceStatus_'
    - '*.Output.LogFile:=MergeVersioningExistAndNotExistFile.Output.LogFile'
    - '*.Output.GCPCloudStorageVersioningStatusReport:=MergeVersioningExistAndNotExistFile.Output.MergedData'
