userObject:
  app:
    name: AzureAppConnector
    appURL: http://localhost.com
    appPort: "0"
    userDefinedCredentials:
      Azure:
        clientID: "$AZURE_CLIENT_ID"
        clientSecret: "$AZURE_CLIENT_SECRET"
        tenantID: "$AZURE_TENANT_ID"
        subscriptionID: "$AZURE_SUBSCRIPTION_ID"
userInputs:
  IncludeCriteria: # "/registry/registry1/repo/repo1/tag/*"
  ExcludeCriteria: # "/registry/registry2/repo/*/tag/*"
fromDate: 2024-08-29
toDate: 2024-08-29
