authors:
- lokesh.b@continube.com
domain: continube
createdDate: 29/04/2024
name: OrganizedOpaReports
displayName: Organized Opa Reports
version: '1.0'
description: Organized Opa Reports
shaToken: ''
showInCatalog: true
icon: fa-solid fa-suitcase
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: DataFile
  description: DataFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: false
- name: LogFile
  description: LogFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: false
outputs:
- name: ComplianceStatus_
  description: Compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: Compliance percentage of the task
  dataType: INT
- name: DataFile
  description: Data File
  dataType: FILE
- name: LogFile
  description: Audit File
  dataType: FILE
