userObject:
  app:
    name: NoCredApp
    appURL: http://localhost.com
    appPort: "0"
    appTags:
      appType:
      - nocredapp
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      NoCred:
        Dummy: ""
userInputs:
  DataFile: "<<MINIO_FILE_PATH>>"
  LogFile : "<<MINIO_FILE_PATH>>"
fromDate: 2024-11-28T04:46:09Z
toDate: 2024-11-28T04:46:09Z