[Variables]
Method = "GET"
CredentialType = "AWSSignature"

[Request]
URL = "https://s3.us-east-1.amazonaws.com/"
Method = "<<Method>>"
ContentType = "application/json"
Redirect = true
CredentialType = "<<CredentialType>>"
TimeOut = 30
Verify = true
MaxWorkers = 5

[Request.Headers]

[Request.Params]

[Request.Retries.RetryOnCondition]
ConditionField = "<<response.status_code>>"
ConditionValue = "503|504|429"
TimeInterval = 2
MaxRetries = 3
RetryBaseDelay = 2
RetryMaxDelay = 60

[Request.Data.Raw]
