[Variables]
Method = "POST"
CredentialType = "AWSSignature"

[Request]
URL = "https://cloudtrail.us-east-1.amazonaws.com/"
Method = "<<Method>>"
Redirect = true
CredentialType = "<<CredentialType>>"
ContentType = "application/json"
TimeOut = 60
Verify = true
MaxWorkers = 5

[Request.Headers]
X-Amz-Target = "com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.LookupEvents"
Content-Type = "application/x-amz-json-1.1"
[Request.Params]

[Request.Retries.RetryOnCondition]
ConditionField = "<<response.status_code>>"
ConditionValue = "503|504|429"
TimeInterval = 2
MaxRetries = 3
RetryBaseDelay = 2
RetryMaxDelay = 60

[Request.Data]
[Request.Data.Raw]
Value = "{\"LookupAttributes\":[{\"AttributeKey\":\"ResourceType\",\"AttributeValue\":\"AWS::S3::Bucket\"}],\"MaxResults\":50}"
 
 