[Variables]
Method = "POST"
CredentialType = "AWSSignature"
Action = "ListUsers"
Version = "2010-05-08"

[Request]
URL = "https://iam.amazonaws.com/"
Method = "<<Method>>"
ContentType = "application/x-www-form-urlencoded"
Redirect = true
CredentialType = "<<CredentialType>>"
TimeOut = 30
Verify = true
MaxWorkers = 5

[Request.Headers]

[Request.Params]
Action = "<<Action>>"
Version = "<<Version>>"

[Request.Retries.RetryOnCondition]
ConditionField = "<<response.status_code>>"
ConditionValue = "503|504|429"
TimeInterval = 2
MaxRetries = 3
RetryBaseDelay = 2
RetryMaxDelay = 60

[Request.Data.URLEncoded]
