[Response]

[Response.RuleSet]

    [Response.RuleSet.AppendColumnCondition]
    ConditionField = "<<response.status_code>>"
    ConditionValue = "200"

    [Response.RuleSet.AppendColumn]
    IncludeAllInputFields = true
    
    [Response.RuleSet.AppendColumn.Fields]

    [Response.RuleSet.PaginationCondition]
    ConditionField = ""
    ConditionValue = ""