[PermissionMappings]
PermissionCreate = "PermissionSetEvent"
PermissionUpdate = "PermissionSetEvent"
PermissionDelete = "PermissionSetEvent"
PermissionCrud = "PermissionSetEvent"
PermissionsApiEnabled = "RestApi"
PermissionsApiUserOnly = "RestApi"
PermissionsEmailSingle = "EmailSingleEvent"
PermissionsEmailMass = "EmailMassEvent"
PermissionsEditTask = "TaskEditEvent"
PermissionsEditEvent = "EventEditEvent"
PermissionsExportReport = "ExportReportEvent"
PermissionsImportPersonal = "ImportPersonalEvent"
PermissionsDataExport = "DataExportEvent"
PermissionsManageUsers = "UserManagementEvent"
PermissionsEditPublicFilters = "PublicFilterEditEvent"
PermissionsEditPublicTemplates = "PublicTemplateEditEvent"
PermissionsModifyAllData = "DataModificationEvent"
PermissionsEditBillingInfo = "BillingInfoEditEvent"
PermissionsManageCases = "CaseManagementEvent"
PermissionsMassInlineEdit = "MassInlineEditEvent"
PermissionsEditKnowledge = "KnowledgeEditEvent"
PermissionsManageKnowledge = "KnowledgeManagementEvent"
PermissionsManageSolutions = "SolutionManagementEvent"
PermissionsCustomizeApplication = "ApplicationCustomizationEvent"
PermissionsEditReadonlyFields = "ReadonlyFieldEditEvent"
PermissionsRunReports = "ReportRunEvent"
PermissionsViewSetup = "SetupViewEvent"
PermissionsTransferAnyEntity = "EntityTransferEvent"
PermissionsNewReportBuilder = "NewReportBuilderEvent"
PermissionsActivateContract = "ContractActivationEvent"
PermissionsActivateOrder = "OrderActivationEvent"
PermissionsImportLeads = "LeadImportEvent"
PermissionsManageLeads = "LeadManagementEvent"
PermissionsTransferAnyLead = "LeadTransferEvent"
PermissionsViewAllData = "DataViewAllEvent"
