[PermissionMappings]
PermissionsApiEnabled = "API"
PermissionsAssignPermissionSets = "PermissionUpdate"
PermissionsAssignTopics = "UITracking"
PermissionsAuthorApex = "ApexExecution"
PermissionsConvertLeads = "DatabaseSave"
PermissionsCreateCustomizeDashboards = "Dashboard"
PermissionsCreateCustomizeReports = "Report"
PermissionsCreateDashboardFolders = "Dashboard"
PermissionsCreateReportFolders = "Report"
PermissionsCreateReportInLightning = "Report"
PermissionsCreateTopics = "UITracking"
PermissionsDeleteTopics = "UITracking"
PermissionsEditEvent = "DatabaseSave"
PermissionsEditTask = "DatabaseSave"
PermissionsEditTopics = "UITracking"
PermissionsManageInternalUsers = "PermissionUpdate"
PermissionsManageIpAddresses = "Login"
PermissionsManageLoginAccessPolicies = "Login"
PermissionsManagePasswordPolicies = "PermissionUpdate"
PermissionsManageProfilesPermissionsets = "PermissionUpdate"
PermissionsManageRoles = "PermissionUpdate"
PermissionsManageSharing = "PermissionUpdate"
PermissionsManageUsers = "PermissionUpdate"
PermissionsModifyAllData = "DatabaseSave"
PermissionsResetPasswords = "PermissionUpdate"
PermissionsRunReports = "Report"
PermissionsTransferAnyEntity = "DatabaseSave"
PermissionsTransferAnyLead = "DatabaseSave"
PermissionsViewAllData = "Report"
PermissionsViewDataLeakageEvents = "TransactionSecurity"
PermissionsViewEventLogFiles = "API"
