apiVersion: v1alpha1
kind: rule
meta:
  name: ListJiraIssues
  purpose: List Jira Issues
  description: List Jira Issues
  labels:
    appType:
    - jiracloud
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - jiracloud
spec:
  inputs:
  inputsMeta__:
  tasks:
  - name: ListJiraIssues
    alias: t1
    type: task
    purpose: List Jira Issues
    description: List Jira Issues
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.JiraIssueList:=t1.Output.JiraIssueList'