// This file is autogenerated. Modify as per your task needs.
package main

import (
	githubconnector "applicationtypes/githubconnector"
)

type UserInputs struct {
	githubconnector.GitHubConnector `yaml:",inline"`
}

type Outputs struct {
	IsValidated       bool
	ValidationMessage string
}
