authors:
- vivek.p@continube.com
domain: continube
createdDate: 26/08/2024
name: ContainerVulnerabilitySummaryReport
displayName: ContainerVulnerabilitySummaryReport
version: '1.0'
description: ContainerVulnerabilitySummaryReport
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: ContainerScanningReport # A unique identifier of the task input
  description: ContainerScanningReport # A concise description of the task input
  dataType: FILE # data type of the input. Available Types STRING, INT, FLOAT, FILE, JSON
  repeated: false # boolean: true | false. true indicates that one or more data type values can be input for this attribute
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: <<MINIO_FILE_PATH>> # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true # boolean: true | false
outputs:
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
- name: ContainerVulnerabilitySummaryReport
  description: ContainerVulnerabilitySummaryReport
  dataType: FILE
- name: LogFile
  description: Log File
  dataType: FILE
