apiVersion: rule.policycow.live/v1alpha1
kind: rule
meta:
  name: GithubPullRequestsRequiredReviewersReport
  purpose: To ensure that all open Pull Requests (PRs) in the specified branch and
    repository meet the required review standards.
  description: To ensure that all open Pull Requests (PRs) in the specified branch and
    repository meet the required review standards.
  labels:
    appType:
      - nocredapp
    environment:
      - logical
    execlevel:
      - app
  app: NoCredApp
  annotations: {}
spec:
  inputs:
    InputFile: <<MINIO_FILE_PATH>>
    OutputMethod: ALL
    PRRequestConfigFile: <<MINIO_FILE_PATH>>
    ReviewersCountColumnTransformConfigFile: <<MINIO_FILE_PATH>>
    CheckReviewersConditionConfig: <<MINIO_FILE_PATH>>
    OutputFileFormat: JSON
    PRResponseConfigFile: <<MINIO_FILE_PATH>>
    Type: Hierarchy
    HierarchyFile: <<MINIO_FILE_PATH>>
    ConfigFile: <<MINIO_FILE_PATH>>
    ReviewersJQExpression: 'map(. + { requested_reviewers_login: (.requested_reviewers | map(.login))
      })'
    LengthReviewersConditionConfig: <<MINIO_FILE_PATH>>
    RequestedReviewersExistConditionConfig: <<MINIO_FILE_PATH>>
    ExtractRequestedReviewersTransformConfigFile: <<MINIO_FILE_PATH>>
    InsufficientReviewersTransformConfigFile: <<MINIO_FILE_PATH>>
    HierarchicalPersonNotExistTransformConfigFile: <<MINIO_FILE_PATH>>
    HierarchicalPersonExistTransformConfigFile: <<MINIO_FILE_PATH>>
    MergeType: APPEND
    ConvertOutputMethod: FIRST
    JQExpression: '    .[]    | .query    | split("/")    | {org: .[1], repo: .[3], branches: (.[5] | split(","))}   | . as $base   | .branches[]   | {org: $base.org, repo: $base.repo, branch: .} '
    PRNumberJQExpression: map(.PRNumber |= floor)
  inputsMeta__:
    - name: InputFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: json
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputMethod
      dataType: STRING
      defaultValue: ALL
      showField: true
      required: true
      allowedValues:
        - FIRST
        - ALL
      repeated: false
      explanation: ''
    - name: PRRequestConfigFile
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: ReviewersCountColumnTransformConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: CheckReviewersConditionConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: OutputFileFormat
      dataType: STRING
      defaultValue: JSON
      showField: true
      required: true
      allowedValues:
        - JSON
        - CSV
        - PARQUET
      repeated: false
      explanation: ''
    - name: PRResponseConfigFile
      dataType: HTTP_CONFIG
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: Type
      dataType: STRING
      defaultValue: Hierarchy
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: HierarchyFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: csv
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: ConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: ReviewersJQExpression
      dataType: STRING
      defaultValue: 'map(. + { requested_reviewers_login: (.requested_reviewers |
        map(.login)) })'
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: LengthReviewersConditionConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: RequestedReviewersExistConditionConfig
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: ExtractRequestedReviewersTransformConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: InsufficientReviewersTransformConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: HierarchicalPersonNotExistTransformConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: HierarchicalPersonExistTransformConfigFile
      dataType: FILE
      defaultValue: <<MINIO_FILE_PATH>>
      format: toml
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: MergeType
      dataType: STRING
      defaultValue: APPEND
      showField: true
      required: true
      allowedValues:
        - APPEND
        - CONCATENATE
      repeated: false
      explanation: ''
    - name: ConvertOutputMethod
      dataType: STRING
      defaultValue: FIRST
      showField: true
      required: true
      allowedValues:
        - FIRST
        - ALL
      repeated: false
      explanation: ''
    - name: JQExpression
      dataType: JQ_EXPRESSION
      defaultValue: '    .[]    | .query    | split("/")    | {org: .[1], repo: .[3], branches: (.[5] | split(","))}   | . as $base   | .branches[]   | {org: $base.org, repo: $base.repo, branch: .} '
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
    - name: PRNumberJQExpression
      dataType: JQ_EXPRESSION
      defaultValue: map(.PRNumber |= floor)
      showField: true
      required: true
      allowedValues: []
      repeated: false
      explanation: ''
  tasks:
    - name: ExtractDataUsingJQV2
      alias: ExtractRepositoryAndBranch
      type: task
      purpose: ExtractDataUsingJQV2
      description: Extract and transform JSON data using JQ expressions. Supports batch
        processing with configurable chunk sizes and error handling for reliable
        processing.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: ExecuteHttpRequestV2
      alias: GetPullRequests
      type: task
      purpose: ExecuteHttpRequestV2
      description: Executes HTTP API requests with configurable authentication, data
        handling, and response processing. Supports batch requests, flexible
        response transformation, and error management for reliable API
        integration and data collection.
      appTags:
        appType:
          - httprequest
        environment:
          - logical
        execlevel:
          - app
    - name: CheckConditionV2
      alias: FilterPullRequests
      type: task
      purpose: CheckConditionV2
      description: Validates data records against configurable conditions. Splits input
        data into matched and unmatched files using criteria such as text
        patterns, number ranges, dates, or CEL expressions. Also supports field
        updates and conditional transformations to ensure compliance and data
        quality.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: AddLengthOfRequestedReviewersColumn
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: GetUserHierarchy
      alias: GetUser Hierarchy
      type: task
      purpose: GetUserHierarchy
      description: To get the heirarchy of the users
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: ExtractRequestedReviewers
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: CheckConditionV2
      alias: CheckLengthOfRequestedReviewers
      type: task
      purpose: CheckConditionV2
      description: Validates data records against configurable conditions. Splits input
        data into matched and unmatched files using criteria such as text
        patterns, number ranges, dates, or CEL expressions. Also supports field
        updates and conditional transformations to ensure compliance and data
        quality.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: CheckConditionV2
      alias: CheckHierarchicalPersonExist
      type: task
      purpose: CheckConditionV2
      description: Validates data records against configurable conditions. Splits input
        data into matched and unmatched files using criteria such as text
        patterns, number ranges, dates, or CEL expressions. Also supports field
        updates and conditional transformations to ensure compliance and data
        quality.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: TransformUsersWithInsufficientReviewers
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        block:
          - block-9
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: TransformUsersWithNoHierarchicalPerson
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        block:
          - block-9
        environment:
          - logical
        execlevel:
          - app
    - name: TransformDataV2
      alias: TransformUsersWithHierarchicalPerson
      type: task
      purpose: TransformDataV2
      description: Transform and manipulate data columns by adding, updating, deleting,
        reordering, or deduplicating fields. Supports conditional logic,
        cross-file data mapping, function-based calculations, and complex
        restructuring for compliance and reporting.
      appTags:
        appType:
          - nocredapp
        block:
          - block-9
        environment:
          - logical
        execlevel:
          - app
    - name: MergeDataV2
      alias: MergeInsufficientReviewersAndNoHierarchyUsers
      type: task
      purpose: MergeDataV2
      description: Combine data from two input files using flexible merge strategies.
        Supports APPEND (stack rows vertically) and CONCATENATE (join columns
        horizontally by position). Handles multiple file formats with error
        handling for reliable integration.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: MergeDataV2
      alias: MergeHierarchyUsersWIthExistingUsers
      type: task
      purpose: MergeDataV2
      description: Combine data from two input files using flexible merge strategies.
        Supports APPEND (stack rows vertically) and CONCATENATE (join columns
        horizontally by position). Handles multiple file formats with error
        handling for reliable integration.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
    - name: ExtractDataUsingJQV2
      alias: ConvertFloatToNumber
      type: task
      purpose: ExtractDataUsingJQV2
      description: Extract and transform JSON data using JQ expressions. Supports batch
        processing with configurable chunk sizes and error handling for reliable
        processing.
      appTags:
        appType:
          - nocredapp
        environment:
          - logical
        execlevel:
          - app
  ioMap:
    - ExtractRepositoryAndBranch.Input.InputFile:=*.Input.InputFile
    - ExtractRepositoryAndBranch.Input.JQExpression:=*.Input.JQExpression
    - ExtractRepositoryAndBranch.Input.OutputMethod:=*.Input.OutputMethod
    - GetPullRequests.Input.RequestConfigFile:=*.Input.PRRequestConfigFile
    - GetPullRequests.Input.ResponseConfigFile:=*.Input.PRResponseConfigFile
    - GetPullRequests.Input.InputFile:=ExtractRepositoryAndBranch.Output.OutputFile
    - FilterPullRequests.Input.InputFile:=GetPullRequests.Output.OutputFile
    - FilterPullRequests.Input.ConditionConfig:=*.Input.CheckReviewersConditionConfig
    - FilterPullRequests.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - AddLengthOfRequestedReviewersColumn.Input.InputFile1:=FilterPullRequests.Output.MatchedConditionFile
    - AddLengthOfRequestedReviewersColumn.Input.TransformConfigFile:=*.Input.ReviewersCountColumnTransformConfigFile
    - AddLengthOfRequestedReviewersColumn.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - GetUser Hierarchy.Input.Type:=*.Input.Type
    - GetUser Hierarchy.Input.InputFile:=AddLengthOfRequestedReviewersColumn.Output.OutputFile
    - GetUser Hierarchy.Input.HierarchyFile:=*.Input.HierarchyFile
    - GetUser Hierarchy.Input.ConfigFile:=*.Input.ConfigFile
    - ExtractRequestedReviewers.Input.InputFile1:=GetUser Hierarchy.Output.OutputFile
    - ExtractRequestedReviewers.Input.TransformConfigFile:=*.Input.ExtractRequestedReviewersTransformConfigFile
    - ExtractRequestedReviewers.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - CheckLengthOfRequestedReviewers.Input.InputFile:=ExtractRequestedReviewers.Output.OutputFile
    - CheckLengthOfRequestedReviewers.Input.ConditionConfig:=*.Input.LengthReviewersConditionConfig
    - CheckLengthOfRequestedReviewers.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - CheckHierarchicalPersonExist.Input.InputFile:=CheckLengthOfRequestedReviewers.Output.MatchedConditionFile
    - CheckHierarchicalPersonExist.Input.ConditionConfig:=*.Input.RequestedReviewersExistConditionConfig
    - CheckHierarchicalPersonExist.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformUsersWithInsufficientReviewers.Input.InputFile1:=CheckLengthOfRequestedReviewers.Output.UnmatchedConditionFile
    - TransformUsersWithInsufficientReviewers.Input.TransformConfigFile:=*.Input.InsufficientReviewersTransformConfigFile
    - TransformUsersWithInsufficientReviewers.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformUsersWithNoHierarchicalPerson.Input.InputFile1:=CheckHierarchicalPersonExist.Output.UnmatchedConditionFile
    - TransformUsersWithNoHierarchicalPerson.Input.TransformConfigFile:=*.Input.HierarchicalPersonNotExistTransformConfigFile
    - TransformUsersWithNoHierarchicalPerson.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - TransformUsersWithHierarchicalPerson.Input.InputFile1:=CheckHierarchicalPersonExist.Output.MatchedConditionFile
    - TransformUsersWithHierarchicalPerson.Input.TransformConfigFile:=*.Input.HierarchicalPersonExistTransformConfigFile
    - TransformUsersWithHierarchicalPerson.Input.OutputFileFormat:=*.Input.OutputFileFormat
    - MergeInsufficientReviewersAndNoHierarchyUsers.Input.InputFile1:=TransformUsersWithInsufficientReviewers.Output.OutputFile
    - MergeInsufficientReviewersAndNoHierarchyUsers.Input.InputFile2:=TransformUsersWithNoHierarchicalPerson.Output.OutputFile
    - MergeHierarchyUsersWIthExistingUsers.Input.InputFile1:=MergeInsufficientReviewersAndNoHierarchyUsers.Output.MergedData
    - MergeHierarchyUsersWIthExistingUsers.Input.InputFile2:=TransformUsersWithHierarchicalPerson.Output.OutputFile
    - ConvertFloatToNumber.Input.InputFile:=MergeHierarchyUsersWIthExistingUsers.Output.MergedData
    - ConvertFloatToNumber.Input.JQExpression:=*.Input.PRNumberJQExpression
    - ConvertFloatToNumber.Input.OutputMethod:=*.Input.OutputMethod
    - '*.Output.CompliancePCT_:=ConvertFloatToNumber.Output.CompliancePCT_'
    - '*.Output.ComplianceStatus_:=ConvertFloatToNumber.Output.ComplianceStatus_'
    - '*.Output.LogFile:=ConvertFloatToNumber.Output.LogFile'
    - '*.Output.GithubPRRequiredReviewersReport:=ConvertFloatToNumber.Output.OutputFile'
