id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: JiraCloud
  displayName: JiraCloud
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - jiracloud
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - jiracloud
  version: ""
spec:
  url: http://localhost.com
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidateJiraCloud
    taskVersion: ""
  credentialTypes:
  - name: BasicAuthentication
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: BasicAuthentication
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses: []
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
isVersionToBeOverride: true
